### ISSUE TITLE
Why does add_graph only use first output node?

### ISSUE THREAD

**Issue by teffland** [lanpa/tensorboardX#137]
[In add_graph](https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboardX/graph.py#L19) at L19 and L38 only the first output node is used.  

Is there a particular reason why?

This is causing `add_graph` to break because my architecture is using `torch.split` which produces multiple outputs. 

I was able to get it working by just iterating over the outputs but wanted to ask before submitting a fix

**Comment by lanpa** [comment]
Because among the models to be tested (those in torchvision), the only module with multiple outputs is `Dropout`. So I ignored it and put a FIXME on L38. Please send your fix. thanks~

**Comment by ml7** [comment]
Following up on this, @teffland do you have your fix?

**Comment by teffland** [comment]
Yeah, just submitted a PR #162

**Comment by lanpa** [comment]
closing because the corresponding PR is merged.
