### ISSUE TITLE
Cannot specify flush_secs as documented

### ISSUE THREAD

**Issue by minostauros** [lanpa/tensorboardX#148]
[Documentation](http://tensorboard-pytorch.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.__init__) gives `flush_secs` as an example of `**kwargs` of `SummaryWriter` class

but it gives

> TypeError: __init__() got an unexpected keyword argument 'flush_secs'

**Comment by lanpa** [comment]
Hi, I can't reproduce. Can you post the full error message?

**Comment by chivee** [comment]
@lanpa , Hi, the pip version didn't contain `**kwargs`.

**Comment by lanpa** [comment]
@chivee  pip version is pretty old. It will be updated this weekend.

**Comment by minostauros** [comment]
@chivee @lanpa Thanks for the updates!
