### ISSUE TITLE
Is it possible to use Prototype the custom-scalars plugin in tensorflow?

### ISSUE THREAD

**Issue by Joshua1989** [lanpa/tensorboardX#161]
Currently, if we want to plot multiple scalars into one plot, we can use `add_scalars` to achieve this.
The problem is that `add_scalars` creates too many subfolders. When tuning hyper-parameters usually we have many different models and by doing this it is hard to manage the scalar curves.

I found [this discussion](https://github.com/tensorflow/tensorboard/issues/300) that it is even possible to use a regex to dynamically create plots with multiple scalars, a more concrete example can be found [here](https://github.com/tensorflow/tensorboard/pull/664). The code is simple but I do not know how to make it possible in tensorboardX.

**Comment by lanpa** [comment]
Yes, that should be simple. @ml7 Are you interested in porting this?
