### ISSUE TITLE
Display of images in embedding visualization provides weird result

### ISSUE THREAD

**Issue by msieb1** [lanpa/tensorboardX#181]
Hello,

when using the add_embedding functionality of the writer class, the following problem appears:

I am feeding in (3, 480, 640) sized RGB-images that I resize to (3, 299, 299). I collect a bunch of those and feed them into the add_embedding function, but instead of displaying the correctly colored sprites, the following appears.

![image](https://user-images.githubusercontent.com/32754403/42119083-84c1ecfe-7bd6-11e8-946f-451af9a13851.png)

How do I make the sprites be displayed correctly?

**Comment by lanpa** [comment]
Random guess:
- Your channel is not order correctly (RGB vs BGR)
- The value is overflowed (>1.0 or <0.0)
