### ISSUE TITLE
Tensorboard dropping messages?

### ISSUE THREAD

**Issue by thedch** [lanpa/tensorboardX#191]
Hi -- thanks for writing this! 

I ran this script:

```
from tensorboardX import SummaryWriter
from datetime import datetime

current_time = datetime.now().strftime('%b%d_%H-%M-%S')
writer = SummaryWriter(log_dir='/home/daniel/logs/'+current_time)

for i in range(100):
    writer.add_text('TAGHERE', 'testStringHere' + str(i))
```

and the tensorboard output is this:
![screen shot 2018-07-20 at 12 52 56 pm](https://user-images.githubusercontent.com/13357734/43022362-e4237140-8c1b-11e8-8a4f-c7bebd3b5621.png)

It seems like the majority of the messages are being dropped. Let me know if I'm doing something wrong, thanks! 😄

**Comment by thedch** [comment]
I updated the script to fix a few issues, but still having the same issue:

```
from tensorboardX import SummaryWriter
from datetime import datetime

current_time = datetime.now().strftime('%b%d_%H-%M-%S')
writer = SummaryWriter(log_dir='/home/daniel/logs/'+current_time)

for i in range(100):
    writer.add_text('TAGHERE', 'testStringHere' + str(i), i) # use global step

writer.close() # close the writer
```

![screen shot 2018-07-20 at 2 15 50 pm](https://user-images.githubusercontent.com/13357734/43025728-be8bdd26-8c27-11e8-89a4-80550e860396.png)

**Comment by zplizzi** [comment]
Try installing from source like mentioned in #180.

**Comment by lanpa** [comment]
install from source dont work, I will looking into this, thanks.

**Comment by zplizzi** [comment]
Yeah, this started happening for me again. It actually looks like it's somehow overwriting data. For example, if I'm logging every step, I'll see data for step 1, and then when step 2 is printed, the output of step 1 disappears and is replaced by the output of step 2. This occurs most of the time, but sometimes the older output stays instead of being replaced, thus resulting in the appearance of intermittent logging.

**Comment by lanpa** [comment]
Found the reason!
see https://github.com/lanpa/tensorboardX/issues/44

the default `event_accumulator.TENSORS` is 10, which is too small.
changing that to a bigger number like 100 fixes this.
