### ISSUE TITLE
add_image_with_boxes

### ISSUE THREAD

**Issue by SarahQiong** [lanpa/tensorboardX#192]
Any examples for using add_image_with_boxes within tensorboardX? 

It seems like this function has a bug:
1. 'SummaryWriter' object has no attribute '_file_writer'.
2. function image_boxes is also not implemented.

**Comment by lanpa** [comment]
Hi, this is not included in the pip package. please  `pip install git+https://github.com/lanpa/tensorboardX` for the newest version.
