### ISSUE TITLE
demo.py - entries in scalar group show up as separate runs

### ISSUE THREAD

**Issue by yaroslavvb** [lanpa/tensorboardX#195]
The example in demo seems to add graphs under scalar group as separate runs instead of grouped graphs under current run, is that intended?
TensorBoard 1.9.0, latest tensorboardX/pytorch from pip 
```
    writer.add_scalars('data/scalar_group', {'xsinx': n_iter * np.sin(n_iter),
                                             'xcosx': n_iter * np.cos(n_iter),
                                             'arctanx': np.arctan(n_iter)}, n_iter)
```
<img width="665" alt="screenshot 2018-07-26 10 40 14" src="https://user-images.githubusercontent.com/23068/43278550-4cc3f65e-90c0-11e8-826b-5873ffdba05d.png">

**Comment by lanpa** [comment]
That was a workaround for the old tensorboard API. Maybe it can be rewrite with the new API  `custom_scalar`
