### ISSUE TITLE
imagepy import error handling message is deceiving

### ISSUE THREAD

**Issue by andres-fr** [lanpa/tensorboardX#200]
As I describe here:

https://stackoverflow.com/a/51592268/4511978

Importing `imagepy`with missing dependencies can raise ImportErrors *for some of the submodules only*. Regarding tensorboardX, these errors are handled in writer.py:

https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/summary.py#L273

But the message (`"add_video needs package moviepy"`) is deceiving, since it is possible to have `moviepy` installed and still get `ImportError`s. In my case, `moviepy` loaded well, but loading `moviepy.editor` failed. I fixed it installing the `requests` package.

-------

Regarding possible solutions, different approaches are possible, and I'm not sure to what extent this is `moviepy`'s or `tensorboardX`'s fault... maybe a more general error message? or first importing `moviepy` only and then importing the editor, each one of them with their own `try...except` and specific message like this?:

```python
def make_video(tensor, fps):
    try:
        import moviepy.editor as mpy
    except ImportError:
        print('add_video needs package moviepy')
        return
    try:
        from moviepy import editor as mpy
    except ImportError:
        print("moviepy is installed, but can't import moviepy.editor. Some dependencies could be missing [imageio, requests]")
        return
    import tempfile
```

**Comment by lanpa** [comment]
The code looks good. Would you make a PR?

**Comment by andres-fr** [comment]
Done! thanks a lot https://github.com/lanpa/tensorboardX/pull/202

**Comment by andres-fr** [comment]
Sorry, travis complained because MPLBACKEND=Agg, will check into that...

**Comment by andres-fr** [comment]
I have no clue, sorry, if anybody can give me a pointer to that one would be glad to work on it

**Comment by andres-fr** [comment]
It was a style issue with flake8. After fixing it, I'm getting this error everywhere:

`The command "pytest" exited with 2.`

And the cause seems to be a missing caffe2?

`CRITICAL:root:Cannot load caffe2.python. Error: /home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state.so: undefined symbol: _ZTIN6caffe27NetBaseE`

Again, any help is welcome!
Cheers

**Comment by lanpa** [comment]
Hi, that should be caused by torch==0.4.1 and caffe2, which is hard to spot. Pinning the CI test to torch==0.4 fixes this Thanks for the PR.

**Comment by andres-fr** [comment]
Good to know! Thanks again

**Comment by lanpa** [comment]
found the root cause: https://github.com/pytorch/pytorch/issues/10249
https://github.com/lanpa/tensorboardX/blob/f243ab0ca28935dbe19608f56a5704c651db780f/tensorboardX/x2num.py#L10
