### ISSUE TITLE
Error occurred while saving PNG image

### ISSUE THREAD

**Issue by hzxie** [lanpa/tensorboardX#210]
It seems that there's something wrong in the function `make_np`.
TensorboardX version: 1.4.0.

**Comment by hzxie** [comment]
In `_prepare_image(I)` function, it assumes that the `ndarray` is ordered as [N]CHW.
However, it is ordered as HWC.

**Comment by hzxie** [comment]
My code works well in TensorboardX 1.2.0.

**Comment by ClementPinard** [comment]
Same problem here, a breaking change occured in june with this PR #156
I don't mind the breakage, but it should at least go with documentation.

**Comment by lanpa** [comment]
Got it. We need a more comprehensive unit test to prevent that happen again.
