### ISSUE TITLE
Is there any way to limit number of images saved in .event ?

### ISSUE THREAD

**Issue by princewang1994** [lanpa/tensorboardX#214]
Hi, these days I meet an issue that when I train semantic segmentation models (such as UNet), I always add lots of input image, target label and predict labels in order for monitoring the process of training.
 But after long time training, all historical images had been saved in my tensorboardX's log file, so XX.event might be huge. Is there any way to limit the size of these just-for-oneshot image(maybe set parm like buffer_size or some way to overwrite old images)? 

thx~

**Comment by lanpa** [comment]
No. But you can greatly reduce the file size by not calling `add_image` too often or only call it after certain epoch has passed. (If you already know something will be purged, you should not save it in the begining.)
