### ISSUE TITLE
Support for latest tensorflow version?

### ISSUE THREAD

**Issue by kaniblu** [lanpa/tensorboardX#216]
The latest tensorflow version (1.10.0) comes with a better tensorboard that can be launched standalone without loading tensorflow onto memory. However, current tensorboardX does not support new tsv data formats, hence the latest tensorboard fails to read embedding summaries written by current tensorboardX. Are there any plans for version update?

**Comment by lanpa** [comment]
It looks good now. I tried on demo.py, examples/demo_embedding.py, examples/demo_multiple_embedding.py
my env:
```
tensorboard (1.10.0)
tensorflow (1.10.1)
```
