### ISSUE TITLE
Error for histogram visualization  (Expected binary or unicode string, got)?

### ISSUE THREAD

**Issue by taochenshh** [lanpa/tensorboardX#217]
Hi, I am using pytorch 0.4.1. And I installed the lastest tensorboardX. I can call writer.add_histogram successfully. But when I use tensorboard to visualize it. It gives me the **TypeError:Expected binary or unicode string, got** .

A minimal example to reproduce the error is:
```python
import numpy as np
from tensorboardX import SummaryWriter
writer = SummaryWriter(log_dir='./log')
v = np.random.uniform(0, 5, (64,3,7,7))
writer.add_histogram('x', v, 0, bins='sqrt')
```
Note: I installed tensorflow 1.10 as well.

**Comment by lanpa** [comment]
I just confirmed the bug (with tensorboard 1.9.0) and will look into this.
a quick work around would be removing the `bins` argument.
`writer.add_histogram('x', v, 0)`

**Comment by lanpa** [comment]
That was a horrible bug. Thanks for the report.

**Comment by themightyoarfish** [comment]
This still happens with `SummaryWriter` with TB 1.12.0 and TBX 1.2.

**Comment by themightyoarfish** [comment]
Wait, it's the version on pypi that is outdated, can you update it?
