### ISSUE TITLE
could not display demo_graph.py

### ISSUE THREAD

**Issue by zironycho** [lanpa/tensorboardX#218]
Here is my version of packages. 
```
tensorboard==1.9.0
tensorboardX==1.2
tensorflow==1.9.0
torch==0.4.1
torchvision==0.2.1
```

and running command like:
`tensorboard --host 0.0.0.0 --logdir tmp demo_graph.py`

and the result is 
`No graph definition files were found.`

Is it working example in my version?

**Comment by lanpa** [comment]
The graph function has not been tested against torch 0.4.1

I will working on this recently.
