### ISSUE TITLE
Support for custom scalars

### ISSUE THREAD

**Issue by tivaro** [lanpa/tensorboardX#219]
Hi, thank you for this very useful tool!
Tensorboard has a really cool [custom scalars](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/custom_scalar) plugin.

Support for this would be super cool!

E.g. have the `add_scalars` method plot using different line styles instead of creating all those additional logs that clutter your legend.

**Comment by lanpa** [comment]
https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_custom_scalars

Hi, I think this is what you want. Reopen the issue if it's not.
