### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by jvmancuso** [lanpa/tensorboardX#221]
It seems like the last tagged version of this repo was 1.2,but PyPI currently has 1.4.  There is currently no mention of which commit lines up with each release.  I suggest all minor versions be tagged here (in the future and for all previous releases), as people installing from pip should, at minimum, be able to view the repo as it existed in any of the PyPI releases.

**Comment by lanpa** [comment]
I totally forget about that. T.T

**Comment by jvmancuso** [comment]
Was going to close this, but tags haven't been created for 1.3 or 1.4.  I don't think non-collaborators can create tags, so looks like it'd be up to you to fix this, @lanpa.  Should be a pretty easy fix, no?

**Comment by lanpa** [comment]
https://pypi.org/project/tensorboardX/
Hi, I think there is no 1.3. Beside tagging, Do I need to anything on pypi?
