### ISSUE TITLE
incorrect ? loop in graph visualization

### ISSUE THREAD

**Issue by xkunglu** [lanpa/tensorboardX#230]
![image](https://user-images.githubusercontent.com/37414026/45909908-d67e4900-bdb9-11e8-924a-f8f8fca8aa35.png)
I hope png attaches, if not heres description. ResNet BasicBlock  forward has a sequence of in-> conv, bnorm,  relu, conv,  bn, +residual,  relu -> out. I presume that since the block definition has only one Relu defined, the resulting graph loops back to the relu node before outputing: which is not whats happening in the data flow: there are 2 relu layers, not a weird loop.

I dunno if this is a tensorboard or a ..X error. But I thought you might want to know.
thanks

**Comment by xkunglu** [comment]
should it not look like this? In spite of the reuse of the relu layer type... 
![image](https://user-images.githubusercontent.com/37414026/45910587-32979c00-bdbf-11e8-94d8-e37c63ec392e.png)

**Comment by xkunglu** [comment]
#here is a repro - just updated from 0.4.0 to 0.4.1. to see if there was any difference and there isnt./
import sys
import torch
from torchvision import models
from tensorboardX import SummaryWriter

rn18 = models.resnet18(pretrained=False)
writer = SummaryWriter(log_dir='resnet18')
writer.add_graph(rn18, torch.randn((1, 3, 224, 224)))
writer.close()

print(torch.__version__)
print(sys.version_info[0:3])
# > 0.4.1.post2
# > (3, 6, 5)

**Comment by xkunglu** [comment]
maybe is actually like this  by design? I looked through your code and read thru the graph trace and the operations are correct. Then I opened the Relu node and see that the flow is correct too. If that is the case, close the issue; if you can add a tag to unroll the graph , to me at least, it would be clearer.  
thanks

**Comment by lanpa** [comment]
I found the root cause: because you  used `self.relu` twice. So the tensor will be send back again and forms a loop. If you double click on the pink ReLU block, there should be two nodes inside, representing each relu operations. To show a graph without cycle, please use `F.ReLU` as shown in `examples/demo_graph.py`. Thanks.
