### ISSUE TITLE
How to start a new line in text?

### ISSUE THREAD

**Issue by hxbai** [lanpa/tensorboardX#236]
Hi, I want to start a new line in text, but '\n' isn't work, such as:
`writer.add_text('lstm', 'This is an lstm\n, This is an lstm', 0)`
but it will show in one line, what should I do?
Thanks.

**Comment by lanpa** [comment]
It supports markdown:
https://github.com/lanpa/tensorboardX/blob/b5ac736ff2e93dac2cd283610e309b38dd20d58d/examples/demo.py#L46
I hope that work for you.

**Comment by hxbai** [comment]
Thanks! That's great!
