### ISSUE TITLE
AttributeError: 'SummaryWriter' object has no attribute 'add_custom_scalars_multilinechart'

### ISSUE THREAD

**Issue by windsor34** [lanpa/tensorboardX#245]
I tried to combine the training accuracy and validation accuracy in one plot with the custom scalars, it keeps give me this error and I don't know why. The Tensorboard can show my training/validation loss and accuracy in four separate plots normally.

My code:
    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch, num_epochs - 1))
        print('-' * 10)
        for phase in ['train', 'val']:
            if phase == 'train':
                scheduler.step()
                model.train() 
            else:
                model.eval() 
            running_loss = 0.0
            running_corrects = 0
            for inputs, labels, filename in tqdm(dataloaders[phase]):
                inputs = Variable(inputs).to(device)
                labels = Variable(labels).to(device)
                optimizer.zero_grad()
                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)
                    _, preds = torch.max(outputs, 1)
                    loss = criterion(outputs, labels)
                    if phase == 'train':
                        loss.backward()
                        optimizer.step()

                running_loss += loss.item()
                running_corrects += torch.sum(preds == labels.data)

            epoch_loss = running_loss / dataset_sizes[phase]
            epoch_acc = running_corrects.double() / dataset_sizes[phase]

            if phase == 'train':
                writer.add_scalar('Train/Loss', epoch_loss, epoch)
                writer.add_scalar('Train/Acc', epoch_acc, epoch)
            else:
                writer.add_scalar('Validation/Loss', epoch_loss, epoch)
                writer.add_scalar('Validation/Acc', epoch_acc, epoch)

            print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                phase, epoch_loss, epoch_acc))

            if phase == 'val' and epoch_acc > best_acc:
                best_acc = epoch_acc
                best_model_wts = model.state_dict()

        writer.add_custom_scalars_multilinechart(['Train/Acc', 'Validation/Acc'], title = 'Accuracy')
        writer.add_custom_scalars_multilinechart(['Train/Loss', 'Validation/Loss'], title='Loss')

**Comment by windsor34** [comment]
Nvm, I used add_scalars to achieve the graph I wanted. Did you remove the add_custom_scalars_multilinechart function in your source code? Actually, I was not able to find the source code as well.....

**Comment by lanpa** [comment]
Did you install from pip?

**Comment by gabegrand** [comment]
I'm seeing the same issue (installed from pip). Looks like SummaryWriter.add_custom_scalars() was not included in the v1.4 release source.

**Comment by lanpa** [comment]
@gabegrand Yup, you need to install via
`pip install git+https://github.com/lanpa/tensorboardX` in order to use this function at this time.
