### ISSUE TITLE
install dependency not installed by setup.py

### ISSUE THREAD

**Issue by lanpa** [lanpa/tensorboardX#249]
current result of running setup.py:
https://gist.github.com/lanpa/266f8d5a718f9191e0d2d271ca3d54da

If comment out: https://github.com/lanpa/tensorboardX/commit/b5ac736ff2e93dac2cd283610e309b38dd20d58d#diff-2eeaed663bd0d25b7e608891384b7298R67

Then the result becomes:
https://gist.github.com/lanpa/1805d817540694fd087a8a1316a8af09

This caused readthedoc's import error. (google.protobuf not found)

**Comment by orionr** [comment]
Is this still an issue now that we've added back the pre-generated *_pb2.py files?

**Comment by lanpa** [comment]
finally fixed!
