### ISSUE TITLE
How to use add_figure()? Why i can't show it in tensorboard correctly. 

### ISSUE THREAD

**Issue by kmyfoer** [lanpa/tensorboardX#257]
here is my code.
```
writer = tensorboardX.SummaryWriter('run/exp-1')
figure = matplotlib.pyplot.figure()
x = np.linspace(-1, 1, 50)
y = 2 * x + 1
plt.plot(x, y)
plt.show()
writer.add_figure("matplotlib/figure", figure)
```

but there is nothing is tensorboard.  Any bug in my code?
And why there is no 'Figure' selection in menu bar?

**Comment by kmyfoer** [comment]
> Wouldn't your code blocked on `plt.show()`?
> 
> There's a demo:
> https://github.com/lanpa/tensorboardX/blob/master/examples/demo_matplotlib.py
You are right，show() actually block . But there is still nothing in my tensorboard and then I notice my torch version is 0.3.1. Maybe it's reason. 
Thank you very much!

**Comment by lanpa** [comment]
The torch version should have nothing to do with this issue. Does the demo work for you?

**Comment by kmyfoer** [comment]
> The torch version should have nothing to do with this issue. Does the demo work for you?


I try it again, it works!   : )
