### ISSUE TITLE
ImportError in using SummaryWriter

### ISSUE THREAD

**Issue by petroskey** [lanpa/tensorboardX#266]
Dear lanpa,

Thank you for your great tensorboardX.
I am trying to use SummaryWriter from tensorboardX, but I have been conflicting with
ImportError: cannot import name 'SummaryWriter'.

My environment is windows10, Anaconda3, pyTorch.
And I ran the demo program on Spyder.

Thank you in advance.

**Comment by lanpa** [comment]
Hi, I need further information. Does that work on ipython?

**Comment by sanjaykr5** [comment]
Hi, I faced the same problem with tensorflow 1.12 and pytorch 0.4.1

**Comment by lanpa** [comment]
@sanjaykr5 What's your result of `pip list|grep tensor`?

**Comment by sanjaykr5** [comment]
@lanpa  tensorboardX                       1.4

**Comment by divyakul1** [comment]
> @lanpa tensorboardX 1.4
> tensorboard 1.12.0
> tensorflow 1.12.0
> 
> But now it is working fine..There was conda environment issue. Thanks!

How did you fix the conda issue? I am able to import tensorboardX on python2 and python3 jupyter notebooks but not on any of the conda environments which I need for torch

**Comment by Anikily** [comment]
I have the same question,how do you solved it ?@sanjaykr5
