### ISSUE TITLE
Issues with add_graph

### ISSUE THREAD

**Issue by Linardos** [lanpa/tensorboardX#268]
I was trying to use add_graph on my recurrent model like so:

```
dummy_input = torch.rand(1, 3, 36, 64)
dummy_state, _ = model.forward(dummy_input)

with SummaryWriter(comment='SalGANplus') as w:
    #model = torchvision.models.vgg19()
    w.add_graph(model, (dummy_input, dummy_state), verbose=False)
```

I got an error saying "Invoked with: OperatorExportTypes.RAW, False"
I thought I'd try an off the shelf model like in the provided examples

```

import torchvision
with SummaryWriter(comment='alexnet') as w:
    model = torchvision.models.alexnet()
    w.add_graph(model, (dummy_input, ))

```

This time I got an error message saying:
```
Error occurs, checking if it's onnx problem...
Your model fails onnx too, please report to onnx team
No graph saved
```
Any thoughts on how to solve this? Could it have to do with my torch version? (it's 0.4.1)

**Comment by lanpa** [comment]
Please update to `pytorch-nightly` and install tensorboardX from source and see if it works. Thanks.
