### ISSUE TITLE
Github installation problems

### ISSUE THREAD

**Issue by MartSlaaf** [lanpa/tensorboardX#270]
Hello!
I'm trying to install tensorboardX from GitHub via pip install git+https://github.com/lanpa/tensorboardX
But there is an error:

build/bdist.macosx-10.7-x86_64/wheel/ does NOT support .pth files

pip install tensorboardX goes ok, but have no latest features like custom scalars.

**Comment by hadim** [comment]
Same error here. Looks related to https://github.com/automl/random_forest_run/commit/f975f947979cd1bc46eca30833f8267c2f71514c

**Comment by andrewkho** [comment]
I'm also having this issue. Looking to github version for S3 support

**Comment by andrewkho** [comment]
This PR #272 seems to prevent it, I'm not sure why though. Thanks @hadim for the pointer

**Comment by lanpa** [comment]
Hi all, I found that while `pip install git+https://github.com/lanpa/tensorboardX` showing the error message, if I clone the repo first and install via `python setup.py install` and the error message is gone. Can anyone help me confirm that?

**Comment by lanpa** [comment]
https://github.com/pypa/pip/issues/4780
