### ISSUE TITLE
Using histogram with FileWriter

### ISSUE THREAD

**Issue by nkcr** [lanpa/tensorboardX#277]
Using `FileWriter` to save histogram stats, I am experiencing the following error when running TensorBoard (which is related to #217):

```bash
Expected binary or unicode string, got [1.0]
```

Here is a sample code that produces the error:

```python
value = np.array([1, 1, 2, 3, 3, 3, 4])
name = "hist/test"

file_writer = tb.FileWriter("logs/")
hist_summary = tb.summary.histogram(name, value, "auto")
file_writer.add_summary(hist_summary, global_step=1)
```

I am using `FileWriter` instead of `SummaryWriter` for legacy reasons.

EDIT:  
Doing the same with `SummaryWriter` works well:

```python
summary_writer = SummaryWriter()
summary_writer.add_histogram(name, value, 1)
```

**Comment by themightyoarfish** [comment]
Same with `SummaryWriter`. This used to work previously and I have only upgraded TensorBoard in the meantime.

**Comment by nkcr** [comment]
You are right! I used the latest version from the git and it works!

Thank you.
