### ISSUE TITLE
NameError: name 'workspace' is not defined

### ISSUE THREAD

**Issue by fcampagne** [lanpa/tensorboardX#282]
I was trying to run with pytorch 1 nightly. I resolved the issue by installing future (pip install future).
The problem was that the test for caffe2 import only caught ImportError, but the missing future packaged caused 
ModuleNotFoundError: No module named 'past'

 line 331, in add_scalar
    self.tensorboard_writer.add_scalar(name,value,self.get_iteration_number(phase_name))
  File "/Users/fcampagne/miniconda3/envs/fastai/lib/python3.7/site-packages/tensorboardX/writer.py", line 333, in add_scalar
    scalar_value = workspace.FetchBlob(scalar_value)
NameError: name 'workspace' is not defined

**Comment by fcampagne** [comment]
The issue describes a workaround, but it would be better to also catch ModuleNotFoundError in addition to ImportError in 

```python
def prepare_caffe2(x, modality):
    try:
        from caffe2.python import workspace
    except ImportError:
        # TODO (ml7): Remove try-except when PyTorch 1.0 merges PyTorch and Caffe2
        # Caffe2 is not installed, disabling Caffe2 functionality
        pass
    x = workspace.FetchBlob(x)
    if modality == 'IMG':
        x = _prepare_image(x)
    return x
```

Should be

```python
def prepare_caffe2(x, modality):
    try:
        from caffe2.python import workspace
    except (ImportError, ModuleNotFoundError):
        # TODO (ml7): Remove try-except when PyTorch 1.0 merges PyTorch and Caffe2
        # Caffe2 is not installed, disabling Caffe2 functionality
        pass
    x = workspace.FetchBlob(x)
    if modality == 'IMG':
        x = _prepare_image(x)
    return x
```

**Comment by tycho01** [comment]
The suggested fix didn't work for me, but I did manage to work around this installing the older release 1.2: `conda install -c conda-forge tensorboardx=1.2`.

**Comment by mt-cly** [comment]
I found the solution in https://discuss.pytorch.org/t/tensorboard-in-pytorch-1-1/44515
run command 'pip/pip3 install future'
