### ISSUE TITLE
add_image does not support 1 channel image, like gray image

### ISSUE THREAD

**Issue by anbai106** [lanpa/tensorboardX#285]
Hi, 

I found that the add_image function does not handle 1 channel image, e.g, [1, 134, 134] (C, W, H). It gave me strange image (contrast inversed image in tensor board).

So I wana ask if this function only supports 3 channel image, like RGB? 

Best

**Comment by lanpa** [comment]
What is the data range of your image? Is that in [0, 1]?

**Comment by anbai106** [comment]
@lanpa Hi, my image range is not in [0, 1]. So is that the problem? I should normalize the image into that range? Actually i just use tensorboardX for visualization for sanity check.

Thanks for your response
