### ISSUE TITLE
Can not add graph for dataparallel model

### ISSUE THREAD

**Issue by bl0** [lanpa/tensorboardX#293]
Hi there, I get a  `KeyError: '322'` when I try to `add_graph` for data parallel model on multiple GPU. Here is a mini-example which can reproduce the error:

So what should I do for this error?

```
import torch
import torchvision.models as models
from tensorboardX import SummaryWriter

device = 'cuda'

net = torch.nn.DataParallel(models.__dict__['resnet50']().to(device))
dump_input = torch.rand((10, 3, 224, 224), device=device)
SummaryWriter('./tmp').add_graph(net, dump_input, verbose=False)
```

**Comment by bl0** [comment]
Yes.

**Comment by lanpa** [comment]
https://github.com/lanpa/tensorboardX/tree/pytorch-1.0-alpha

Hi, I have tested that the error is fixed with the above version (install from source)+ pytorch 1.0.0 stable.

**Comment by lanpa** [comment]
![image](https://user-images.githubusercontent.com/2005323/49699757-13ffaf00-fc10-11e8-83c5-09a28aaa3397.png)

**Comment by bl0** [comment]
Thanks. I will try it.
