### ISSUE TITLE
KeyError: '12' when executing add_graph() with an LSTMCell

### ISSUE THREAD

**Issue by CrohnEngineer** [lanpa/tensorboardX#297]
### Hi everyone,  
  
I have seen different issues regarding the **add_graph()** function, but none of them really helped me in solving my problem.  
I have an autoencoder based on a single `torch.nn.LSTMCell` (example code below), from which I am taking the cell state representation and applying a linear transformation in order to have a "decoded" version of the input (long story short: I need to verify the encoding capability of the LSTM state cell representation of the input with respect to a classic autoencoder).  
I am currently using tensorboardX for logging the training and validation loss curves and adding the graph of the network, but while with other architectures everything works smoothly (**really nice work guys, tensorboardX is great!**), when I am trying to add this network graph with the **add_graph()** function, it reports the following error (I am using the `verbose=True` option of the function):  

```
graph(%0 : Float(5, 625)
      %1 : Float(400, 625)
      %2 : Float(400, 100)
      %3 : Float(400)
      %4 : Float(400)
      %5 : Float(625, 100)
      %6 : Float(625)) {
  %7 : Float(5, 400) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%0, %1, %3), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %8 : Float(5, 100) = onnx::Constant[value=<Tensor>](), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %9 : Float(5, 400) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%8, %2, %4), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %10 : Float(5, 400) = onnx::Add(%7, %9), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %11 : Float(5!, 100), %12 : Float(5!, 100), %13 : Float(5!, 100), %14 : Float(5!, 100) = onnx::Split[axis=1, split=[100, 100, 100, 100]](%10), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %15 : Float(5, 100) = onnx::Sigmoid(%11), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %16 : Float(5, 100) = onnx::Sigmoid(%12), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %17 : Float(5, 100) = onnx::Tanh(%13), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %18 : Float(5, 100) = onnx::Mul(%16, %8), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %19 : Float(5, 100) = onnx::Mul(%15, %17), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %20 : Float(5, 100) = onnx::Add(%18, %19), scope: LSTMAutoEncoder/LSTMCell[encodeLayer]
  %21 : Float(5, 625) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%20, %5, %6), scope: LSTMAutoEncoder/Linear[decodeLayer]
  return (%21);
}

Traceback (most recent call last):
  File "/nas/home/ecannas/Tesi/code/verdoliva_remote/demo_error_lstm.py", line 63, in <module>
    writer.add_graph(model, x, verbose=True)
  File "/nas/home/ecannas/miniconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 520, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/nas/home/ecannas/miniconda3/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 104, in graph
    list_of_nodes = parse(graph)
  File "/nas/home/ecannas/miniconda3/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 76, in parse
    n['inputs'][i] = mapping[s]
KeyError: '12'

Process finished with exit code 1

```

As a beginner with tensorboardX and Python in general, I am not sure of what is happening, but it seems to me that the _parse_ function is unable to access one of the nodes of the graph (the one with index '12').   
**Does anyone have any suggestion in order to fix that?**  
Beside this error, the network works fine and I am able to log scalars and visualize training and validation curves.    
I am currently using:

-  `pytorch 0.4.1`
-  `tensorboard 1.12.0`
-  `tensorboardX 1.4`
-  `tensorflow 1.12.0`

My example code for recreating the error:

```
import torch
import torch.nn as nn
from tensorboardX import SummaryWriter


class LSTMAutoEncoder(nn.Module):
    """
        Autoencoder based on an LSTM model with a single cell
        Args:
              input_length (int): input dimension
              code_length (int): hidden input representation (state dimension)
    """

    ##  Constructor
    def __init__(self, input_length, code_length):
        super(LSTMAutoEncoder, self).__init__()

        #  Attributes
        self.input_length = input_length
        self.code_length = code_length

        #  Layers
        self.encodeLayer = nn.LSTMCell(self.input_length, self.code_length)
        self.decodeLayer = nn.Linear(self.code_length, self.input_length)

    ##  Encode function
    def encode(self, x):
        # CODING (simple state encoding by the LSTMCell)
        hx, cx = self.encodeLayer(x)

        return cx

    ##  Decode function
    def decode(self, x):
        # DECODING (linear dense layer followed by an activation function [identity in this case, so none])
        x = self.decodeLayer(x)
        return x

    ##  Forward function
    def forward(self, x):
        encoded = self.encode(x)
        decoded = self.decode(encoded)
        return decoded


###    Execution    ###

##  Parameters

log_dir = '../tensorboard_logs/verdoliva_remote/LSTM_training_proto/demo_error'  # logging directory for tensorboard
train_batch_size = 5
input_length = 625
code_length = 100

if __name__ == '__main__':

    #  Model instantiation
    model = LSTMAutoEncoder(input_length, code_length)

    #  SummaryWriter instatiation
    writer = SummaryWriter(log_dir=log_dir)
    x = torch.randn(train_batch_size, input_length)
    writer.add_graph(model, x, verbose=True)
    writer.close()
```

### Thank you everyone for the attention!

**Comment by lanpa** [comment]
Please try pytorch 1.0.0 stable + https://github.com/lanpa/tensorboardX/tree/pytorch-1.0-alpha

Your code runs without error. (The node grouping function of tensorboardX is under construction though)

![image](https://user-images.githubusercontent.com/2005323/49699787-76f14600-fc10-11e8-9c02-d6ebfaa190e5.png)

**Comment by CrohnEngineer** [comment]
Hey @lanpa ,

thanks for your reply! Following your suggestion everything works smoothly 😁
Thanks again for your time!

> Please try pytorch 1.0.0 stable + https://github.com/lanpa/tensorboardX/tree/pytorch-1.0-alpha
> 
> Your code runs without error. (The node grouping function of tensorboardX is under construction though)
> 
> ![image](https://user-images.githubusercontent.com/2005323/49699787-76f14600-fc10-11e8-9c02-d6ebfaa190e5.png)
