### ISSUE TITLE
support Nx1xHxW and list of tensor for add_images?

### ISSUE THREAD

**Issue by wangg12** [lanpa/tensorboardX#315]

**Comment by lanpa** [comment]
Please reopen if you have a good solution addressing comments in 03be164. Thanks.

**Comment by wangg12** [comment]
For list of images, I think we could assume the sizes are the same and use np.array() to convert it. If the sizes mismatch, an error could be raised.

**Comment by lanpa** [comment]
Good point. Reopening this.
