### ISSUE TITLE
Unable to execute add_graph()

### ISSUE THREAD

**Issue by chinmay5** [lanpa/tensorboardX#317]
While trying to use the feature of aff_graph(), I get the error 

`AssertionError                            Traceback (most recent call last)
<ipython-input-3-3dd99d84a2c6> in <module>()
      3 model = Meso4()
      4 w = SummaryWriter(comment='Meso4')
----> 5 w.add_graph(model, (dummy_input, ),)

~/anaconda3/lib/python3.5/site-packages/tensorboardX/writer.py in add_graph(self, model, input_to_model, verbose, **kwargs)
    564                     print('add_graph() only supports PyTorch v0.2.')
    565                     return
--> 566             self.file_writer.add_graph(graph(model, input_to_model, verbose))
    567         else:
    568             # Caffe2 models do not have the 'forward' method

~/anaconda3/lib/python3.5/site-packages/tensorboardX/pytorch_graph.py in graph(model, args, verbose, omit_useless_nodes)
    216         return graph
    217 
--> 218     assert LooseVersion(torch.__version__) >= LooseVersion("1.0.0")
    219 
    220     with torch.onnx.set_training(model, False):

AssertionError: `

I am using Pytorch version `0.4.1 post 2` while the torchvision version is 1.6 (I upgraded it using pip install torchvisionX --upgrade). Can someone please help me out here

**Comment by lanpa** [comment]
Please use torchvisionX v1.4 for legacy pytorch.

**Comment by chinmay5** [comment]
Thank you for the quick response. Just one followup though, when I try to execute the program, I just get an output of `Error occurs, No graph saved` Is there some way to get a more detailed response in here

**Comment by lanpa** [comment]
Welcome, so which pytorch/tensorboardX combination are you using now? I didn't do much error handling for `add_graph`, please post your minimal reproducible code if possible so I can make improvement based on that.

**Comment by chinmay5** [comment]
Hi. I was able to solve the issue. It was more on my end and I needed to tweak some parameters. I think simply using version 1.4 of tensorboardX was sufficient to solve the issue. Thank you so much

**Comment by fengz63** [comment]
> Hi. I was able to solve the issue. It was more on my end and I needed to tweak some parameters. I think simply using version 1.4 of tensorboardX was sufficient to solve the issue. Thank you so much

**Comment by fengz63** [comment]
> Hi. I was able to solve the issue. It was more on my end and I needed to tweak some parameters. I think simply using version 1.4 of tensorboardX was sufficient to solve the issue. Thank you so much

Thank you for solving my problem!
