### ISSUE TITLE
when I run scalar demo, there are just black.

### ISSUE THREAD

**Issue by Anikily** [lanpa/tensorboardX#320]
<img width="1034" alt="2019-01-09 4 30 09" src="https://user-images.githubusercontent.com/40237123/50886694-12eab900-142c-11e9-9c87-656f346ad878.png">

and the code as bellow:
`from tensorboardX import SummaryWriter
import numpy as np

writer = SummaryWriter()
for epoch in range(100):
    writer.add_scalar('scalar/test',np.random.randn(),epoch)
    writer.add_scalars('scalar/scalar_test',{'xsinx':epoch*np.sin(epoch),'xcosx':epoch*np.cos(epoch)},epoch)
writer.close()
`
what's wrong with me?

**Comment by lanpa** [comment]
What's your tensorboard version?

**Comment by Anikily** [comment]
@lanpa 
tensorboard               1.12.2                    
tensorboardX              1.6                      
tensorflow                0.11.0rc0

**Comment by lanpa** [comment]
I run your code without a problem.
My env:
tensorboard                        1.12.2
tensorflow                         1.12.0

**Comment by lanpa** [comment]
Maybe clean up your logging directory first will help.

**Comment by Anikily** [comment]
but are you using tensorboardX?@lanpa

**Comment by lanpa** [comment]
Considering this a web rendering issue. Not related to this project. Close~
