### ISSUE TITLE
runs don't get grouped correctly and different metrics and up in the same plot

### ISSUE THREAD

**Issue by LeanderK** [lanpa/tensorboardX#328]
When using tensorflow and tensorboard, every run get's correctly grouped, but with tensorboard-x i get one run for every scalar! Like: "name/validation/log_like_mean" as an individual run.
There's also this weird behaviour where I have different scalars in the same plot. I have a validation-plot, where different metrics like "name/validation/log_like_mean", "name/validation/log_like_out_mean" etc. get all placed in.

**Comment by lanpa** [comment]
Hi, can you show some code to reproduce. What function are you using? (add_scalar or add_scalars)

**Comment by LeanderK** [comment]
I solved it, it was my fault. I called `add_scalars`, but I wanted to call `add_scalar`
