### ISSUE TITLE
Type mismatch in `embedding.make_sprite()` when calling `writer.add_emebdding()`

### ISSUE THREAD

**Issue by Johnny-Wish** [lanpa/tensorboardX#335]
# Description
I have been trying to run something like
`writer.add_embedding(embedding, label_img=label_image)`, where embedding is an `embedding` matrix (order-2 Tensor), and `label_image` is a Tensor of shape (N, C, W, H) representing a batch of images.

The code works fine for `label_image` with a dtype of `torch.float32`.

However, if `label_image` are of dtype `torch.float64` (i.e., a `DoubleTensor`), there will be an error traceback

> File "/usr/local/lib/python3.6/site-packages/tensorboardX/writer.py", line 658, in add_embedding
> make_sprite(label_img, save_path)
>File "/usr/local/lib/python3.6/site-packages/tensorboardX/embedding.py", line 31, in make_sprite
> nrow ** 2 - label_img.size(0), *label_img.size()[1:]) * 255), 0)
> RuntimeError: Expected object of scalar type Double but got scalar type Float for sequence elment 1 in sequence argument at position #1 'tensors'

# Possible Cause
I looked at the code and found that this was caused by how tensorboardX makes sprites. Namely, in `make_sprite()` of `embedding.py`, the code `label_img = torch.cat((label_img, torch.randn(xxxxxx), 0)` assumes `label_img` is `float32` (Float) Tensor. The call to `torch.randn` only returns a torch.float32 Tensor. When the first argument `label_img` is `DoubleTensor`, the call to `torch.cat` will raise a RuntimeError about the types.

# Proposed Solution
Either force convert `label_img` to `torch.float32` with `label_img.float()` in `make_sprite()`, or convert the `torch.randn()` tensor dynamically to match `label_img`.

**Comment by lanpa** [comment]
Thanks for the proposal~
