### ISSUE TITLE
Bug with _prepare_video method

### ISSUE THREAD

**Issue by zhaobozb** [lanpa/tensorboardX#347]
Hi 

I found there is a bug in the following code:
```
# pad to nearest power of 2, all at once
def _prepare_video(V):
    import numpy as np
    b, t, c, h, w = V.shape

    if V.dtype == np.uint8:
        V = np.float32(V) / 255.

    def is_power2(num):
        return num != 0 and ((num & (num - 1)) == 0)

    # pad to nearest power of 2, all at once
    if not is_power2(V.shape[0]):
        len_addition = int(2**V.shape[0].bit_length() - V.shape[0])
        V = np.concatenate(
            (V, np.zeros(shape=(len_addition, c, t, h, w))), axis=0)

    n_rows = 2**((b.bit_length() - 1) // 2)
    n_cols = b // n_rows

    V = np.reshape(V, newshape=(n_rows, n_cols, t, c, h, w))
    V = np.transpose(V, axes=(2, 0, 4, 1, 5, 3))
    V = np.reshape(V, newshape=(t, n_rows * h, n_cols * w, c))

    return V
```
The `np.concatenate()` tries to concatenate `V(b, t, c, h, w)` with `(len_addition, c, t, h, w)` on the first axis, which is not possible.

The `V = np.reshape(V, newshape=(n_rows, n_cols, t, c, h, w))` tries to reshape V with shape `(b+len_addition, t, c, h, w)` to `(n_rows, n_cols, t, c, h, w)`, but `n_rows * n_cols` may not equal to `b+len_addition` based on the current code.

**Comment by lanpa** [comment]
Hi, can you show some numbers to fail this code?

**Comment by etienne87** [comment]
also i don't think you can just reshape tensors like this without permuting axes first, it seems the code fails when c > 1
