### ISSUE TITLE
add_scalar displaying bugs

### ISSUE THREAD

**Issue by anbai106** [lanpa/tensorboardX#349]
Hi,

I found a bug to display the training accuracy in tensorboard. My batch size is 5, I evaluate the training accuracy on each batch after each iteration and display it on tensorboard. As the batch size is 5, the resulting accuracy could only be 0.0; 0.2; 0.4; 0.6; 0.8 and 1. 

However, here is the plots:
![image_training](https://user-images.githubusercontent.com/16743978/52263603-db3e3680-292f-11e9-9d65-651720b42802.png)

I only trained a toy data set for i epoch, 12 iterations. We can see from the image, we have some 0.4325 for the 4-th step (orange line is for training).

If I download the training results as csv file, the results are correct:
![capture du 2019-02-05 10 24 02](https://user-images.githubusercontent.com/16743978/52263723-2d7f5780-2930-11e9-9b50-ba54ca2e5e47.png)

Could you help me figure out what happend? Did I calculate the wrong global steps? I saw there are two 0 step in the csv files.

Thanks in advance 

Hao

**Comment by lanpa** [comment]
In tensorboard page, there is a Smoothing option on the left. Set it to zero should solve your issue.

**Comment by anbai106** [comment]
@lanpa Thanks so much, I was so stupid… 

Cheers
