### ISSUE TITLE
add_pr_curve does not aggregate data

### ISSUE THREAD

**Issue by zippeurfou** [lanpa/tensorboardX#356]
This might be the intended behavior (since I am not an heavy tensorboard user) but I find the pr curve pretty useless as it is now.
See this gif to understand what I mean:
![screen recording 2019-02-15 at 07 46 pm](https://user-images.githubusercontent.com/4520383/52891758-107e2c00-315b-11e9-857c-dc6c53850ae4.gif)

I am going to test it with the raw pr curve to see if it is any better but I was wondering if it was a bug or intended behavior.

**Comment by lanpa** [comment]
Hi, have you see the code in `examples/demo.py`? I think for each step you logged, the number of TP/FP/TN/FN should be the same across different steps.

**Comment by zippeurfou** [comment]
Thanks for the answer.
Closing it. I found my error was that I was rounding my prediction meanwhile it is looking for raw prediction (ie. 0.8 and not 1).
