### ISSUE TITLE
add_embedding not working with s3 log dir

### ISSUE THREAD

**Issue by zippeurfou** [lanpa/tensorboardX#358]
I just tried to reproduce one of the example using a log dir that is on s3 instead of locally and this did not write anything (without any error) on the s3 bucket.
here is a minimal example:
```
#create data
import keyword
import torch
 meta = []
 while len(meta)<100:
     meta = meta+keyword.kwlist # get some strings
 meta = meta[:100]

 for i, v in enumerate(meta):
     meta[i] = v+str(i)
 label_img = torch.rand(100, 3, 10, 32)
 for i in range(100):
     label_img[i]*=i/100.0
#write file
from tensorboardX import SummaryWriter
writer = SummaryWriter(log_dir="s3://bucket_name/playground/logs/test")
writer.add_embedding(torch.randn(100, 200), metadata=meta,tag="testing/test")
```
`aws s3 ls s3://bucket_name/playground/logs/test` has nothing in it (actually the test folder is not even created)

When I try to do use local file by changing the `log_dir` in `SummaryWriter` it does work.
I also tried to manually call `writer.file_writer.flush()` after the `add_embedding` but it does nothing.
I am using the master branch.

**Comment by snard6** [comment]
I noticed the same thing. I hacked around it with this:
https://github.com/snard6/tensorboardX/commit/056bba6757e6ef64a8acc58097c25fe0c66d5f5f

Essentially it uses the current embedding files, but if it sees s3:// in the url it saves it to the /tmp directory and uploads them to s3. There's probably a more elegant way to handle this, but it works for my needs.

**Comment by zippeurfou** [comment]
Should we consider doing a PR as a hotfix until we get something more elegant?

**Comment by snard6** [comment]
Here's the PR if the maintainers are interested:
https://github.com/lanpa/tensorboardX/pull/426
