### ISSUE TITLE
embeding not working with tensorbard 1.12

### ISSUE THREAD

**Issue by JamesLuoau** [lanpa/tensorboardX#360]
pip list|grep tensor
tensorboard            1.12.2     
tensorboardX           1.6        
tensorflow             1.12.0     
tensorflow-probability 0.5.0      

download https://github.com/lanpa/tensorboardX/blob/3a4c848ca850015ef5b2c7184dbe65da4eb674f4/examples/demo_embedding.py and embeding not showing in tensorboard. I see tensorboard need tf.saver to create embedings, maybe related to this?

Thanks

**Comment by lanpa** [comment]
I didn't see the `need tf.saver` message. (using the same env as yours) Can you post the whole message?

**Comment by lanpa** [comment]
And I found the it is not shown by default. You have to select it from the drop down list.
![image](https://user-images.githubusercontent.com/2005323/53698810-987f5980-3e1c-11e9-9386-0a373afa1b2b.png)

**Comment by shiranD** [comment]
I have different settings
tensorboard          1.13.0
tensorboardX         1.6
tensor flow           1.13.1
torch                      1.0.1

And the choosing in the dropdown Projector refers me to an issue with the saver as mentioned (refuses to load them)
Would be happy to learn about a solution, and thanks for the effort and time put in to this!

**Comment by lanpa** [comment]
@shiranD Does `examples/demo_embedding.py` works for you?

**Comment by shiranD** [comment]
It does seem to produce embedding. And right before I updated pytorch to be compliant with the Tensorboard version I was able to see the embedding produced by `examples/demo_embedding.py`. Perhaps it is related to the combination of the new versions? Also perhaps related to my graph rep. (A comment I left on a different issue)
