### ISSUE TITLE
__new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by iodncookie** [lanpa/tensorboardX#363]
pip install -U protobuf.

**Comment by Toni-Antonova** [comment]
didn't work for me

**Comment by Toni-Antonova** [comment]
i've tried installing different versions of protobuf and nothing does it

**Comment by iodncookie** [comment]
> i've tried installing different versions of protobuf and nothing does it

if you are using python3,uninstalled the existing installation using pip. Then installed again by **pip3 install protobuf**

**Comment by lanpa** [comment]
@Toni-Antonova Which version are you using? (be sure to uninstall all protobuf before install)

**Comment by youkaichao** [comment]
uninstall first and then install, it works for me.
just `pip install -U protobuf` does not work.

**Comment by VictorZuanazzi** [comment]
I got the same problem. I had to uninstall tensorboardX, unistall protobuf and then install both of them again. It is working now.
