### ISSUE TITLE
[feature] detect NaN and show warning

### ISSUE THREAD

**Issue by lanpa** [lanpa/tensorboardX#377]
It turns out my values were NaN, I've fixed my bug.
Still, it would have been helpful if the error message told me that the values being NaN was the problem.

_Originally posted by @yoonholee in https://github.com/lanpa/tensorboardX/issues/222#issuecomment-470023674_

**Comment by jvanheugten** [comment]
Can we undo that it shows a warning, or a more descriptive one? It's not clear if it is tensorboardX or pytorch, and where it is coming from and for which summary.
Also there is nothing wrong with having NaN values for the scalar summaries.

**Comment by lanpa** [comment]
That was #469 :)
