### ISSUE TITLE
visdom init kwargs

### ISSUE THREAD

**Issue by justusschock** [lanpa/tensorboardX#378]
Is there a way to specify the port, server and other configurations for for the visdom server using `VisdomWriter` or `TorchVis`?

We want to use it on our cluster with multiple users, which should log to private visdom servers.

EDIT:
We are looking for something like I manually did in cfe795b574393f9b6d5f3e52167011f0ed14592a and dcfe49e47588cc13be69fb9c9b4a24ca6bdda272

**Comment by lanpa** [comment]
thanks for the PR!
