### ISSUE TITLE
"tensoarboardX" typo in wiki

### ISSUE THREAD

**Issue by cpnota** [lanpa/tensorboardX#385]
In the "Before Debugging" section it says to type:

`pip install tensoarboardX --upgrade`

This will probably not fix the user's issues. 😄

**Comment by lanpa** [comment]
The wiki is really outdated and needs some fix :)

**Comment by ducalpha** [comment]
Got the same problem. The typo should be fixed since it consumed me 5 minutes to figure out :)

**Comment by cpnota** [comment]
Thanks @ducalpha! @lanpa to be totally clear, the typo is that it says "ten**soar**boardX" (with an extra a) instead of "ten**sor**boardX". The command is still good advice I think.

**Comment by lanpa** [comment]
fixed!
