### ISSUE TITLE
Optionally disable logging for distributed training

### ISSUE THREAD

**Issue by pluiez** [lanpa/tensorboardX#395]
Hi, when I perform training on multiple servers, the summary writer should be only enabled on the master node. However currently there seems no such option to disable SummaryWriter. Will you please support this feature?

**Comment by lanpa** [comment]
Hi, I would like to know how do you distinguish master node from slave nodes. By IP address, environment variables or anything else? thanks.

**Comment by pluiez** [comment]
Hi, thanks for your attention. In pytorch, we can determine the master node by torch.distributed.get_rank() if the returned value is 0. I'm not sure how this is done in other frameworks, such as tensorflow. But a single  server  can simulate mutliple nodes at the same time, so I think IP address is not an applicable identifier.

**Comment by briankosw** [comment]
@pluiez The best way to do it would be to use rank == 0 as your way of distinguishing the master node. In both the cases of Data Parallel and Distributed Data Parallel systems, the default master GPU/node is 0, so it is easiest if you use your master node 0 to do the logging and writing summaries. This is regardless of if you do a single node or multiple node system.

**Comment by lanpa** [comment]
So now we have a new parameter `write_to_disk=True` for SummaryWriter. By setting that to false, the afterward calls to `writer.add_[x]` will have no effect. This should meet your need. Please reopen the issue if needed.

**Comment by harryhan618** [comment]
Hello! Here's a solution from [mmdetection](https://github.com/open-mmlab/mmdetection).
``` python
import functools
def master_only(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        rank = torch.distributed.get_rank()
        if rank == 0:
            return func(*args, **kwargs)

    return wrapper
```

Then warp the method in class with `master_only` decorator. e.g. :
``` python
@master_only
def add_scalar(self, tag, scalar_value, global_step=None, walltime=None):
    ...
```

I think this works fine.
