### ISSUE TITLE
Cannot import name 'SummaryWriter'

### ISSUE THREAD

**Issue by rahulptel** [lanpa/tensorboardX#399]
I am trying to do `from tensorboardX import SummaryWriter`. However, I get the following error.

Traceback` (most recent call last):
  File "file.py", line 10, in <module>
    from tensorboardX import SummaryWriter
  File "some/path/file.py", line 10, in <module>
    from tensorboardX import SummaryWriter
ImportError: cannot import name 'SummaryWriter'

I am running this in an anaconda environment on ubuntu 16.04 with following dependencies. 

`tensorboard==1.13.1`
`tensorboardX==1.6`
`tensorflow==1.13.1`
`tensorflow-estimator==1.13.0`
`torch==1.0.1.post2`
`torchvision==0.2.2`

I can somehow import in the python shell of the same environment. But running the script gives the above error.

**Comment by lanpa** [comment]
Hi, can you show me the directory listing of `some/path/`?

**Comment by rahulptel** [comment]
Seems to be working fine now. the name of the file was `tensorboardX.py`. I changed it to a different name and its working. 

Thanks.
