### ISSUE TITLE
API docs for previous versions and tags are missed for versions>1.2?

### ISSUE THREAD

**Issue by ljqcava** [lanpa/tensorboardX#400]
Firstly, thanks for your project！

I noticed that APIs vary with the different versions. But we can only access to the latest version's API docs on [the project site](https://tensorboardx.readthedocs.io/en/latest/index.html#). Could you generate the API docs for the previous versions (e.g., 1.2, 1.4)?

Moreover, I noticed the release tags are only updated to version==1.2. Is it possible to update the release tags for later versions?

**Comment by lanpa** [comment]
both are updated, thanks.

**Comment by ljqcava** [comment]
@lanpa Thanks!
And what are the general compatible Pytorch versions for each release? For example, for `tensorboardX=1.6.0`, it seems that some source codes will check `assert torch.__version__>='1.0.0'`. 
Maybe it will be better to add version compatibility in release tags, just like what you wrote in release tag for [`version1.2`](https://github.com/lanpa/tensorboardX/releases/tag/v1.2).
