### ISSUE TITLE
pytorch_graph.parse not backwards compatible

### ISSUE THREAD

**Issue by skruseman** [lanpa/tensorboardX#402]
Code using tensorboardX.pytorch_graph.parse() written for tensorboardX < v1.6 will break after upgrade to v1.6. When not providing the second argument 'args', it will default to None which will then fail on the line:
    n_inputs = len(args) # not sure...

```
from tensorboardX import pytorch_graph
pytorch_graph.parse(my_graph)
```

**Comment by lanpa** [comment]
Users are not supposed to use undocumented API directly. So the compatibility is not guaranteed.
