### ISSUE TITLE
_prepare_video messing up video

### ISSUE THREAD

**Issue by josiahls** [lanpa/tensorboardX#408]
**Describe the bug**
I am trying to add a video with the [b, t, c, h, w] requirements. I am finding that the lines:
```python
    V = np.reshape(V, newshape=(n_rows, n_cols, c, t, h, w))
    V = np.transpose(V, axes=(3, 0, 4, 1, 5, 2))
    V = np.reshape(V, newshape=(t, n_rows * h, n_cols * w, c))
```
Are messing up the video. It would help to comment why they are even here. Is this to remove the "batch" dimension?

During debug, the above code screws up the image. I understand that this is for the moviepy but.... why do all this? This seems more complicated than what moviepy actually needs? Let me know, I am making a fork and fixing this.

**Minimal runnable code to reproduce the behavior**
```python
from tensorboardX import SummaryWriter
import pybulletgym.envs

writer = SummaryWriter()
env.reset()
env.render(mode="rgb_array")
env.reset()
for i in range(100):
    # Recording
    frames = np.zeros((1, 1, 3, 240, 320), dtype=np.int)
    for t in range(10):
                frame_rgb = np.rollaxis(env.render(mode='rgb_array'), 2, 0)
                frame_rgb_with_time = np.expand_dims(frame_rgb, 0)
                frames = np.hstack((frames, np.expand_dims(frame_rgb_with_time, 0)))
    writer.add_video('data/best_run', torch.from_numpy(frames), i)
...
```

**Expected behavior**
It shouldn't look so fugly...

**Screenshots**
What I am expecting:
![image](https://user-images.githubusercontent.com/19930483/56009143-c32ac080-5cac-11e9-99be-429c0397063a.png)

What I am getting:
![2019-04-11 22-58-54 2019-04-11 22_59_31](https://user-images.githubusercontent.com/19930483/56009350-86ab9480-5cad-11e9-8a4b-bab1fa57e6d8.gif)

**Environment**
What is the result of 
`pip list|grep -E "torch|proto|tensor"`
protobuf               3.6.1       
tensorboard            1.12.2      
tensorboardX           1.6         
tensorflow             1.12.0      
tensorflow-probability 0.5.0       
torch                  1.0.1.post2 
torchvision            0.2.1   

**Additional context**
I am doing a reinforcement algorithm. I want to be able to see the best/highest reward robot actions.

**Comment by lanpa** [comment]
Hi, I guess you install via pip.

This should have been fixed in #390 

Can you try again by installing from source?
