### ISSUE TITLE
Corrupt axes from add_figure() method

### ISSUE THREAD

**Issue by diogoseca** [lanpa/tensorboardX#412]
The output of a given figure is the following in Jupyter:
![output of figure in jupyter](https://user-images.githubusercontent.com/6810578/56459005-ccd7b680-6385-11e9-8b3a-cfd179ae78aa.png)

But in tensorboard, the following shows up:
![output of add_figure in tensorboard](https://user-images.githubusercontent.com/6810578/56458992-98fc9100-6385-11e9-9957-c549fa123c32.png)

I digged a little bit into it and found that the problem resides in https://github.com/lanpa/tensorboardX/blob/05b17d125cfd1a0dddb2ae599a2eb72b39bedcf3/tensorboardX/utils.py#L22-L23

Got any tips on how to solve this problem?

**Comment by diogoseca** [comment]
I've found a way to work around it. 

Instead of calling SummaryWriter.add_figure, I call SummaryWriter.add_image, but instead of passing a figure as an argument, I pass a numpy array which is the result of the following function:
```
import matplotlib.pyplot as plt
import matplotlib as mplt
import numpy as np
from io import BytesIO

def figure_to_arr(figure, close=True):
    buf = BytesIO()
    figure.savefig(buf, format='png', bbox_inches='tight', transparent=False)
    if close:
        plt.close(figure)
    buf.seek(0)
    arr = mplt.image.imread(buf, format='png')[:,:,:3]
    arr = np.moveaxis(arr, source=2, destination=0)
    return arr
```

**Comment by lanpa** [comment]
I have a similar thought like yours. and I think another way is call methods of `figure` to change the figure property before calling `add_figure`.
