### ISSUE TITLE
How do I hide view() operation in a graph?

### ISSUE THREAD

**Issue by brorro** [lanpa/tensorboardX#417]
Hi, I added a graph and ..
The graph shows operations of torch.Tensor.view()
```
def forward(self, x):
    x = self.conv1(x)
    x = self.conv2(x)
    x = self.pull1(x)
    x = self.conv3(x)
    x = self.pull2(x)

    x = x.view(x.size(0), -1)

    x = self.linear(x)
```

![Screenshot from 2019-05-02 23-53-47](https://user-images.githubusercontent.com/11650176/57084629-9dd22500-6d35-11e9-9004-20caecfbc11e.png)

It definitely annoys me.... Is there any way to make a clean graph?

**Comment by lanpa** [comment]
How about wrap view in a class so that those nodes will be hidden by default?
