### ISSUE TITLE
About visualization sparseconvnet

### ISSUE THREAD

**Issue by fruityangyang** [lanpa/tensorboardX#419]
Dear author, thank you very much for sharing so much an amazing project! Now, i'm trying to use tensorboardX to visualize the network which is newly defined by the sparseconvnet. Some layers are rewrited by their authour. I have encountered a killed result and nothing is output. So my question is, can tensorboardX support to visualize any pytorch projects?

**Comment by lanpa** [comment]
No. Only a subset of models is visually verified. But we are working with pytorch developers on this. Please post the failing model and we can check on that.
