### ISSUE TITLE
[Feature Request] TensorBoard mesh plugin support

### ISSUE THREAD

**Issue by VladislavZavadskyy** [lanpa/tensorboardX#427]
Hello, I would love to see [this plugin](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/mesh) supported by tensorboardX. 
I don't have the time to gain a reasonable understanding of how the whole system of tensorboardX works to be able to integrate it properly. However, I offer my collaboration to someone who does (or has this understanding already) and also wishes to see it happen.

**Comment by lanpa** [comment]
This is ongoing:) https://github.com/pytorch/pytorch/pull/20413

**Comment by VladislavZavadskyy** [comment]
Great! Thanks for pointing it out.
I think it's worth leaving this open until this feature is added.

**Comment by VladislavZavadskyy** [comment]
I see it was [merged](https://github.com/pytorch/pytorch/commit/b5a5e296aa2f3fad6b2f99f87644237837bf3c82). Thank you guys for your work!
