### ISSUE TITLE
Request for Multiple images on one experiment (add max_outputs argument)

### ISSUE THREAD

**Issue by veritas9872** [lanpa/tensorboardX#430]
In the current implementation of TensorboardX add_image function, there is no max_outputs parameter as in Tensorboard.

This makes it somewhat inconvenient to write multiple output images in one session, which a very useful feature.

The Tensorflow [documentation](https://www.tensorflow.org/api_docs/python/tf/summary/image) states the following.

"The tag in the outputted Summary.Value protobufs is generated based on the name, with a suffix depending on the max_outputs setting:

1. If max_outputs is 1, the summary value tag is 'name/image'.
2. If max_outputs is greater than 1, the summary value tags are generated sequentially as 'name/image/0', 'name/image/1', etc."

Is there any way to manage the number of image using the tag?

If so, could this be explained in the documentation? 

If not, I would like to request that the "max_outputs" argument be added to the add_image and add_images functions.

**Comment by lanpa** [comment]
From your description, the effect of `max_outputs` acts nothing but adding a suffix. Do you want to limit the number of images saved?

**Comment by veritas9872** [comment]
I think it would be great if there were a simple API for saving multiple images from the same training round. Most people (including myself) have a bit of trouble implementing this by ourselves.
