### ISSUE TITLE
Is it necessary to call SummaryWriter.close() after each add_something call in order to update the board?

### ISSUE THREAD

**Issue by kwasnydam** [lanpa/tensorboardX#438]
Hello. 

I am trying to write a small wrapper around tensorboardX and its SummaryWriter class for my project. I have noticed, that it is necessary for me to call the _.close()_ method each time I input some new record in order to have the tensorboard display something: otherwise I see _unable to get first event timestep for <directory>_ error in tensorboard terminal. If I call the .close() method every time, tensorboard updates normally. Is it necessary to call this method in this scenario then?

**Comment by lanpa** [comment]
Hi, I have exposed `flush()` for SummaryWriter in #451. You may try that after it's merged.
