### ISSUE TITLE
.add_image() method does not record the events when called in a loop without pauses.

### ISSUE THREAD

**Issue by kwasnydam** [lanpa/tensorboardX#439]
**Describe the bug**
When trying to test the _add_image()_ method in a simple for loop, I noticed that regardless of using the _close()_ method on the _SummaryWriter_, the created event file is empty. If I add a pause after the call, events are created correctly.

**Minimal runnable code to reproduce the behavior**
```
from tensorboardX import SummaryWriter
import numpy as np
writer = SummaryWriter()
for i in range(10):
    writer.add_image('test_image', np.random.randn(8, 16), dataformats='HW', global_step=i)
writer.close()
...
```

**Expected behavior**
Correct event file is created and add_image() events are correctly interpreted. Tensorboard displays an image under tag _test_image_ with 10 data points.

**Current Behavior**
0 kB event file is created and tensorboard does not display any images.

**Platform**
Windows 7, 
tensorboard 1.13.1
tensorboardX 1.7
tensorflow 1.13.1

**Additional context**
After adding a time.pause(1) after the _add_image()_ call, the images are saved and displayed properly.

```
from tensorboardX import SummaryWriter
import numpy as np
import time 


writer = SummaryWriter()
for i in range(10):
    writer.add_image('test_image', np.random.randn(8, 16), dataformats='HW', global_step=i)
    time.pause(1)
writer.close()
...
```

**Comment by lanpa** [comment]
I tested on my machine, and the result is slightly different than yours. Using your unpaused code, my tensorboard can still show `10` images and if I commented out the `writer.close()`, it only shows `7` images. Maybe this is OS dependent. A possible fix is here: https://github.com/lanpa/tensorboardX/pull/451, after it is merged, you can either pass the `flush_sec`  to the SummaryWriter constructor or call `writer.flush()` manually and see if that works. Thanks.
