### ISSUE TITLE
add_image() won't work without NVIDIA GPU

### ISSUE THREAD

**Issue by blDraX** [lanpa/tensorboardX#450]
**Describe the bug**
When calling add_image() for a CPU FloatTensor, it still fails in case there is no NVIDIA GPU available. The reason for this is an assert in summary.py which will check whether the tensor is an instance of torch.cuda.FloatTensor. This causes the following behaviour:
```
python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    writer.add_image("tag", a, 1)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorboardX/writer.py", line 277, in add_image
    self.file_writer.add_summary(image(tag, img_tensor), global_step)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorboardX/summary.py", line 157, in image
    assert isinstance(tensor, np.ndarray) or isinstance(tensor, torch.cuda.FloatTensor) or isinstance(tensor, torch.FloatTensor), 'input tensor should be one of numpy.ndarray, torch.cuda.FloatTensor, torch.FloatTensor'
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

**Minimal runnable code to reproduce the behavior**
```
import torch
from tensorboardX import SummaryWriter

a = torch.FloatTensor(3, 1, 1)
a.zero_()
writer = SummaryWriter()
writer.add_image("tag", a, 1)
```

**Expected behavior**
add_image() works successfully for CPU FloatTensor even if no NVIDIA GPU is installed.

**Environment**
tensorboard (1.13.1)
tensorboard-pytorch (0.7.1)
tensorflow (1.13.1)
tensorflow-estimator (1.13.0)
torch (1.1.0)
torchvision (0.3.0)

**Additional context**
Issue is fixed if order of checks in assert is modified as short-circuit behaviour of **or** will cause no check for cuda.FloatTensor if CPU FloatTensor was already successfully confirmed:
`assert isinstance(tensor, np.ndarray) or isinstance(tensor, torch.FloatTensor) or isinstance(tensor, torch.cuda.FloatTensor), 'input tensor should be one of numpy.ndarray, torch.FloatTensor, torch.cuda.FloatTensor'`

**Comment by lanpa** [comment]
Hi, tensorboard-pytorch (0.7.1) is pretty old...
I have tested your code on mac (without GPU) without problem.
