### ISSUE TITLE
add_mesh() raise ValueError as the number of vertices increase

### ISSUE THREAD

**Issue by JMingKuo** [lanpa/tensorboardX#452]
**Describe the bug**
add_mesh() raise ValueError as the number of vertices increase

**Minimal runnable code to reproduce the behavior**
```
import meshzoo

points, cells = meshzoo.iso_sphere(2)
vertices = points
colors = np.ones_like(vertices, dtype=np.int32) * 255
faces = cells

vertices = np.expand_dims(vertices, 0)
colors = np.expand_dims(colors, 0)
faces = np.expand_dims(faces, 0)

vertices_tensor = torch.as_tensor(vertices)
faces_tensor = torch.as_tensor(faces)
colors_tensor = torch.as_tensor(colors)

writer = SummaryWriter()
writer.add_mesh('mesh_color_tensor', vertices=vertices_tensor, faces=faces_tensor,
                colors=colors_tensor)
```

**Expected behavior**
It works fine with smaller mesh "meshzoo.iso_sphere(1)"

**Screenshots**
![image](https://user-images.githubusercontent.com/21190587/59738832-2fb9d100-9295-11e9-8798-609674445861.png)
ValueError: b'\x12\x11mesh_color_tensor\x18\x01*\x04null2\x04\x01\xa2\x01\x03' has type str, but isn't valid UTF-8 encoding. Non-UTF-8 strings must be converted
to unicode objects before being added.

**Environment**
pytorch 1.1.0
tensorboardX 1.7
meshzoo 0.4.3

**Additional context**

**Comment by lanpa** [comment]
Finally I found the root cause: https://github.com/tensorflow/tensorflow/pull/12867/files

This issue also helps me solve other tensorboardX issues.

Thanks.
