### ISSUE TITLE
Change print statement to logging.warning

### ISSUE THREAD

**Issue by kernelmachine** [lanpa/tensorboardX#457]
It would be helpful if this print statement was changed to a logging.warning, to be able to suppress the warning in downstream applications: https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/x2num.py#L13

Happy to make the quick PR if necessary!

**Comment by lanpa** [comment]
Definitely. There's already many usages of `logging` in tensorboardX. PRs are welcome.
