### ISSUE TITLE
add_video dataformats (misleading pip release notes) ? 

### ISSUE THREAD

**Issue by botforge** [lanpa/tensorboardX#471]
I noticed https://pypi.org/project/tensorboardX/ release 1.7 specifies the ability to send "dataformats" as a parameter for videos, but I checked `writer.py` and `summary.py` and found this to not be true (it is, however, true for images). I'd be down to include support for "CHW" and "HWC" shaped tensors.

**Comment by lanpa** [comment]
I think I mistyped the release note. Please use the API described in: https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_video 

And it is easy to support other dataformats for video by extending the function for 5D input: https://github.com/lanpa/tensorboardX/blob/97a57c0604c9c6b7bea43668a50f7331b909807e/tensorboardX/utils.py#L98 Feel free to open a PR.
