### ISSUE TITLE
module 'tensorboard.lazy' has no attribute 'LazyLoader'

### ISSUE THREAD

**Issue by MiaoQiaowei** [lanpa/tensorboardX#472]
File "D:\Anaconda\envs\tensorflow_gpu\lib\site-packages\tensorboard\__init__.py", line 25, in <lambda>
    mod = lambda i: lazy.LazyLoader(i[i.rindex('.') + 1:], globals(), i)
AttributeError: module 'tensorboard.lazy' has no attribute 'LazyLoader'

I dont know how to fix it. Please help me.
Thanks in advance

**Comment by lanpa** [comment]
please follow the issue template.
