### ISSUE TITLE
UserWarning: ONNX export failed on ATen operator atan2 because torch.onnx.symbolic.atan2 does not exist   .format(op_name, op_name))

### ISSUE THREAD

**Issue by kernelizd** [lanpa/tensorboardX#477]
**Describe the bug**

I'm trying add_graph and I get those four errors
`C:\Users\s4551072\AppData\Local\conda\conda\envs\python36\lib\site-packages\torch\onnx\utils.py:586: UserWarning: ONNX export failed on ATen operator atan2 because torch.onnx.symbolic.atan2 does not exist
  .format(op_name, op_name))
C:\Users\s4551072\AppData\Local\conda\conda\envs\python36\lib\site-packages\torch\onnx\utils.py:586: UserWarning: ONNX export failed on ATen operator empty because torch.onnx.symbolic.empty does not exist
  .format(op_name, op_name))
C:\Users\s4551072\AppData\Local\conda\conda\envs\python36\lib\site-packages\torch\onnx\utils.py:586: UserWarning: ONNX export failed on ATen operator fill because torch.onnx.symbolic.fill does not exist
  .format(op_name, op_name))
C:\Users\s4551072\AppData\Local\conda\conda\envs\python36\lib\site-packages\torch\onnx\utils.py:586: UserWarning: ONNX export failed on ATen operator index because torch.onnx.symbolic.index does not exist
  .format(op_name, op_name))`

**Minimal runnable code to reproduce the behavior**
```
from tensorboardX import SummaryWriter

def crelu(re, im):
    return nn.functional.relu(re), nn.functional.relu(im)


def zlogit(re, im):
    abs_ = t.sqrt(re ** 2 + im ** 2)
    ang = t.atan2(im, re)
    mask = ~(ang > 0)
    clone = abs_.clone()
    clone[mask] = -1 * abs_[mask]
    return clone


class Clinear(nn.Module):
    def __init__(self, in_, out_):
        super(Clinear, self).__init__()
        self.Lre = nn.Linear(in_, out_)
        self.Lim = nn.Linear(in_, out_)

    def forward(self, re, im):
        return self.Lre(re) - self.Lim(im), self.Lre(im) + self.Lim(re)

class CDan(nn.Module):
    def __init__(self):
        super(CDan, self).__init__()
        self.feat1 = Cconv1d(in_channels=30, out_channels=60, kernel_size=2, stride=1, padding=2)
        self.feat2 = Cconv1d(in_channels=60, out_channels=120, kernel_size=3, stride=2, padding=0)
        # self.feat3 = nn.MaxPool1d(kernel_size=4)
        self.featl1 = Clinear(6360, 500)
        self.featl2 = Clinear(500, 31)
        self.featl3 = nn.Softmax(dim=1)

    def forward(self, x):
        re, im = x[Ellipsis, 0], x[Ellipsis, 1]
        op0re, op0im = crelu(*self.feat1(re, im))
        op1re, op1im = crelu(*self.feat2(op0re, op0im))
        # op2re, op2im = self.feat3(op1re), self.feat3(op1im)
        op2re, op2im = op1re.view(x.shape[0], -1), op1im.view(x.shape[0], -1)
        op3re, op3im = crelu(*self.featl1(op2re, op2im))
        op4re, op4im = crelu(*self.featl2(op3re, op3im))
        op = zlogit(op4re, op4im)
        return self.featl3(op)


my_net = CDan().to(device)
writer.add_graph(my_net, next(iter(dataloader_target))[0], verbose=True)

...
```

**Expected behavior**

**Screenshots**

**Environment**
What is the result of 
`pip list|grep -E "torch|proto|tensor"`
If the version is too old, please try to update first.

**Python environment**
Which version of python are you using? Did you use Andconda or Virtualenv?
Anaconda venv

**Additional context**
I'm using latest versions of Pytorch and TB, that is, 1.1 and 1.14 respectively.

**Comment by lanpa** [comment]
So What is the result of
pip list|grep -E "torch|proto|tensor"

**Comment by lanpa** [comment]
onnx is no longer used in tensorboardX. 
With tensorboardX1.9 / pytorch 1.3, the following code works well.
So, closing this.

```python
from tensorboardX import SummaryWriter
import torch.nn as nn
import torch



class MathOP(nn.Module):
    def __init__(self):
        super(MathOP, self).__init__()

    def forward(self, x, y):
        return torch.atan2(x, y)

m = MathOP()
x = torch.Tensor([1])

with SummaryWriter() as writer:
    writer.add_graph(m, (x, x))

```
