### ISSUE TITLE
Input to tensorboard add_graph is not a Tensor 

### ISSUE THREAD

**Issue by pcy1302** [lanpa/tensorboardX#482]
What should I do if the input to my model not only consists of Tensors but also python lists?

That is,

    model = Net()
    add_graph(model, (Tensor1, Tensor2, list))
In this case, I get errors. How can I pass a list as an input to ````add_graph````?

**Comment by lanpa** [comment]
What are the error messages?

**Comment by lanpa** [comment]
see #520
