### ISSUE TITLE
weird bug when passing images to label_img argument

### ISSUE THREAD

**Issue by HareshMiriyala** [lanpa/tensorboardX#484]
**Describe the bug**
I have an image Tensor of shape (40641, 3, 128, 64) that i'm passing to label_img argument . My embeddings are of shape (40641,256). 

I get this weird error  : 

writer.add_embedding(val_embeddings_ocl,metadata=val_labels_ocl,label_img=torch.Tensor(images_array))
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 824, in add_embedding
    make_sprite(label_img, save_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/embedding.py", line 38, in make_sprite
    arranged_augment_square_HWC[:arranged_img_HWC.shape[0], :, :] = arranged_img_HWC
ValueError: could not broadcast input array from shape (25856,12928,3) into shape (12928,12928,3)

**Environment**
What is the result of 
`pip list|grep -E "torch|proto|tensor"`
If the version is too old, please try to update first.

tensorboardX (1.8+366bc8f)

**Python environment**
Python 3.6

**Comment by lanpa** [comment]
https://github.com/tensorflow/tensorboard/issues/670

This is a tensorboard restriction. I will add a parameter doc for this. Thanks.

**Comment by lanpa** [comment]
And btw, there's also a bug on tensorboardX too. Will be fixed together.
