### ISSUE TITLE
use tensorboardx in miniconda

### ISSUE THREAD

**Issue by JsBlueCat** [lanpa/tensorboardX#485]
i install tensorboardx in docker  by pip 

but when i call tensorboard it throws out this error 
``` bash
bash: tensorboard: command not found
```
environment
pytorch 1.1
torchvision 0.3.0
tensorboardx 1.8
miniconda
python 3.7

does miniconda support tensorboard???

**Comment by JsBlueCat** [comment]
does it support cuda10?

**Comment by gforge** [comment]
It works with miniconda, check out my Docker-file: https://github.com/gforge/Gocker/blob/master/PyTorch/nnx-pytorch/Dockerfile

I'm not sure why you need cuda support for tensorboard, but I use 10 and don't have any issues.

**Comment by lanpa** [comment]
They are separate packages. just `pip install tensorboard` or `pip install tensorflow` then you can run tensorboard.
