### ISSUE TITLE
 AssertionError: %34 : Tensor = onnx::Unsqueeze[axes=[0]](%32)  has empty scope name

### ISSUE THREAD

**Issue by msieb1** [lanpa/tensorboardX#487]
Getting the error

`AssertionError: %34 : Tensor = onnx::Unsqueeze[axes=[0]](%32)
 has empty scope name`

when calling

```
import torch
import torchvision
from tensorboardX import SummaryWriter

dummy_input = torch.Tensor(1, 3, 224, 224)

with SummaryWriter(comment='alexnet') as w:
    model = torchvision.models.alexnet()
    w.add_graph(model, (dummy_input, ))
```

I am using Pytorch 1.1.0 and TensorboardX 1.8

**Comment by lanpa** [comment]
I tried your code with
```
torch                         1.1.0
torchvision                   0.3.0
```
and
```
torch                         1.2.0
torchvision                   0.4.0
```

and the graph rendered without a problem. Would you like to try the master branch as well?
(https://github.com/lanpa/tensorboardX/commit/9b9933aa6b614de32341142533e7cf9594cdc2c4)

**Comment by lanpa** [comment]
No reply for 2 months. Considering the issue is solved.
