### ISSUE TITLE
Error using `add_hparams`

### ISSUE THREAD

**Issue by RSKothari** [lanpa/tensorboardX#502]
**AttributeError: 'EnumTypeWrapper' object has no attribute 'STATUS_SUCCESS'**
Attempted to use add_hparams when compiled from source. TensorboardX version `1.8+9b9933a`

**Minimal runnable code to reproduce the behavior**
```
from tensorboardX import SummaryWriter
writer = SummaryWriter()
writer.add_hparams({'lr': 1e-5, 'bsize': 20, 'n_hidden': 100}, {'accuracy': 0, 'loss': 0})
...
```

**Expected behavior**
 I followed the example file [here](https://github.com/lanpa/tensorboardX/blob/master/examples/demo_hparams.py) 

**Screenshots**
![image](https://user-images.githubusercontent.com/10388010/63808245-8115ba80-c8ed-11e9-8678-c6403b5ddfca.png)

**Environment**
What is the result of 
`pip list|grep -E "torch|proto|tensor"`
![image](https://user-images.githubusercontent.com/10388010/63808322-adc9d200-c8ed-11e9-8496-fd339e7df06c.png)

**Python environment**
Which version of python are you using? Did you use Andconda or Virtualenv? No

**Comment by tmac1997** [comment]
@RSKothari hi, did you make any progress on this issue? I encountered same problem in jupyter notebook. Don't know if it works in terminal.

**Comment by RSKothari** [comment]
Hi @tmac1997 , sorry I gave up on trying to use hparams. I haven't visualized its output either. Will be sure to post any updates.

**Comment by clefourrier** [comment]
I solved this issue (occuring in PyCharm as well as terminal) by updating to protobuf 3.9.1 (which will not help @RSKothari but might help @tmac1997 )

**Comment by tmac1997** [comment]
@clefourrier Thanks! This really helps solve my problem. I'm wondering how did find the solution?

**Comment by clefourrier** [comment]
@tmac1997 I followed the code execution step by step, and did not notice anything unusual. Then, I saw here that RSKothari does not have this problem when using the terminal, which means that it can work with his environment. Since his version of protobuf was not the same as mine, I updated, and it fixed my problem.

**Comment by lanpa** [comment]
https://github.com/protocolbuffers/protobuf/issues/6028

**Comment by lanpa** [comment]
Thank you for sorting the problem out! @RSKothari @clefourrier
