### ISSUE TITLE
Question about add_Graph function's argument "input_to_model"

### ISSUE THREAD

**Issue by zhanlaoban** [lanpa/tensorboardX#503]
First, thanks for the contribution of this great tensorboardX.
Second, I try to visualize the network structure graph of a text classification--TextCNN in NLP. The beginning of the network is the embedding layer. The question is how do I define the argument "input_to_model" of "writer.add_graph()"?

**Comment by lanpa** [comment]
Hi, that is usually the usual input tensor that you will feed into the model. If still not working please post a simple code section and I can check for you. Reopen the issue if needed, thanks.
