### ISSUE TITLE
TenosorboardX can only display up to 10 images.

### ISSUE THREAD

**Issue by xubin1994** [lanpa/tensorboardX#504]
I saved a lot of pictures, but only 10 pictures can be displayed at a time. Is there an interface that can be set?
![image](https://user-images.githubusercontent.com/28856641/63988550-5acf6500-cb0f-11e9-956d-9da23555bf66.png)

**Comment by mdraw** [comment]
This number can be configured in the tensorboard server options, see https://stackoverflow.com/a/52178270
