### ISSUE TITLE
Is tensorboardX the same as torch.utils.tensorboard?

### ISSUE THREAD

**Issue by KovenYu** [lanpa/tensorboardX#506]
I noticed that the source code seems alike. Is it exactly the same?

I'm asking these because I have multiple versions of branches that use tensorboardX/utils.tensorboard so I wonder whether I can use the same code with switching between these two sources.

Thanks in advance.

**Comment by lanpa** [comment]
Not exactly the same. torch.utils.tensorboard is more pytorch specific while TensorBoardX is more framework agnostic.
