### ISSUE TITLE
save the t-SNE figure

### ISSUE THREAD

**Issue by cmhungsteve** [lanpa/tensorboardX#507]
Can we directly save the t-SNE or PCA figure instead of printing the screen?

Thank you

**Comment by lanpa** [comment]
t-SNE and PCA are rendered (and computed) by your browser. TensorboardX only forwards the data to tensorboard. I suggest using existing libraries for saving the figure. see: https://towardsdatascience.com/visualising-high-dimensional-datasets-using-pca-and-t-sne-in-python-8ef87e7915b
