### ISSUE TITLE
audio amplitude out of range, auto clipped

### ISSUE THREAD

**Issue by haqkiemdaim** [lanpa/tensorboardX#511]
Hi there just want to ask something regarding the warning below:

```
> def audio(tag, tensor, sample_rate=44100):
>     tensor = make_np(tensor)
>     tensor = tensor.squeeze()
>     if abs(tensor).max() > 1:
>         print('warning: audio amplitude out of range, auto clipped.')
>         tensor = tensor.clip(-1, 1)
```
1. What are the reason if i'am getting the warning on my terminal during training at the end of the validation phase?

2. At which part of my audio data that i should modify to avoid my audio from being clipped?

2. What would be the effect on my output if im getting the warning?

Looking forward to see your explanation on this :)

**Comment by lanpa** [comment]
1: The warning explains itself: the input has values not are in the defined range, which is [-1, 1].
2, 3: It depends on how many data points were clipped. If very few of them were clipped, a human is not able to spot the difference. On the other hand, the resulting sound should be much uncomfortable. To avoid the clipping, you can normalize the input by yourself. For example, `x = x/max(x)`

**Comment by DrHaqkiem** [comment]
> 1: The warning explains itself: the input has values that are outside of the defined range, which is [-1, 1].
> 2, 3: It depends on how many data points were clipped. If very few of them were clipped, a human is not able to spot the difference. On the other hand, the resulting sound should be much uncomfortable. To avoid the clipping, you can normalize the input by yourself. For example, `x = x/max(x)`

1. Im sory but im not really clear what [-1,1] indicates correspond to my audio data.

2. The clipping occur at the end of every epoch of the training. Quite a lot.

3. Again i didn't get what do you mean by 'normalize the input'. What are the features of my audio that I need to modify ya?

**Comment by lanpa** [comment]
1. It's math notation. x in [-1,1] means -1 <= x <= 1.
2. So, is there anything that is only done at the end of every epoch?
3. I mean to normalize the input of add_audio. It should be a series of numbers.

**Comment by haqkiemdaim** [comment]
@lanpa hey there, again just want to ask,
what if i just comment the clipping code:

> #tensor = tensor.clip(-1, 1)

because i noticed that the clipping make my loss become higher AND

I still confuse on:

> To avoid the clipping, you can normalize the input by yourself. For example, x = x/max(x)

Where is exactly the part of the code should i add the above normalization operation ya?

And one more thing, i still don't understand:

1.  Why the need of clipping ya?
2.  Is it mean that my audio amplitude is very high? Should i edit my audio amplitude on the audio editor before i start the training?

sory again if i ask a lot ..

**Comment by lanpa** [comment]
Hi, I don't think the clipping operation will affect the training loss. The data you passed (which should be some output from your network) is first cloned and then been applied the clip if necessary.

For the second question, lets take imageNet classification as an example. The classification score is represented as a 1000-dim vector and its value is not guaranteed to lie in [0, 1]. To make them in [0, 1], you can either add a sigmoid layer after the last layer or compute the maximum of the output and divide all of the elements by that max value. Even more, you can clip the value by yourself before passing to add_audio.

Why the need of clipping ya?  -> to meet the data format standard.
Is it mean that my audio amplitude is very high? Should i edit my audio amplitude on the audio editor before i start the training?  -> maybe. check the datatype carefully and inspect each layer's output if possible.
