### ISSUE TITLE
add_embedding() writes too large sprite.png images for TB frontend

### ISSUE THREAD

**Issue by pdpino** [lanpa/tensorboardX#516]
**Describe the bug**

When writing embeddings and using the Projector tab in TB, the TB frontend has a maximum size for sprite images of 8192x8192 px (`sprite.png` saved). The method `writer.add_embedding(...)` allows writing sprite images greater than said dimensions. If that happens, the Tensorboard frontend fails with the following:

```
Error: Sprite image of dimensions 16384px x 16384px exceeds maximum dimensions 8192px x 8192px
```

After this, the Project tab can't be used (see screenshot below).

**Minimal runnable code to reproduce the behavior**
```
import torch
from tensorboardX import SummaryWriter

writer = SummaryWriter(log_dir="/example/log/dir")

n_images = 1000
image_size = 512

embeddings = torch.ones(n_images, 100) # Number of features is not relevant
images = torch.ones(n_images, 3, image_size, image_size)

writer.add_embedding(embeddings, label_img=images, tag="reproduce-bug")
```

**Expected behavior**

The `writer.add_embedding(...)` method could catch this case and raise an exception, to prevent saving a `sprite.png` image greater than maximum dimensions.

**Screenshots**

Error displayed by the Tensorboard frontend:
![image](https://user-images.githubusercontent.com/20805451/66160810-506a2480-e601-11e9-8685-0afc825a3ba3.png)
![image](https://user-images.githubusercontent.com/20805451/66160892-7abbe200-e601-11e9-94a1-4378c4dd4925.png)

**Environment**

Using Ubuntu 16.04.5.
Result of running: `pip list|grep -E "torch|proto|tensor|tb"`
```
protobuf           3.9.1         
pytorch-ignite     0.2.0         
tb-nightly         2.1.0a20190928
tensorboardX       1.8           
torch              1.1.0         
torchvision        0.4.0 
```

**Python environment**
* python: 3.5
* pip: 19.2.3
* virtualenv: 15.0.1

**Additional context**

* One may have multiple embeddings saved in the `log_dir`, but when the TB frontend finds this error for at least one of the embeddings, the projector tab can't be used (see screenshot), until the too-large-sprite is deleted from disk.
Though this specific behavior comes from to TB frontend, if TensorboardX catches the error before saving the sprite, the `log_dir` corruption could be avoided.

* [Here](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/projector/vz_projector/data-provider.ts#L479) is the line of code that raises the error in the Tensorboard frontend

**Proposed solution**

An assert statement in `add_embedding()` before calling `make_sprite()` [here](https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/writer.py#L861), or inside `make_sprite()` before saving the sprite to disk, [here](https://github.com/lanpa/tensorboardX/blob/master/tensorboardX/embedding.py#L47).

Note that the sprite width and height is `N**0.5 * W`, where `N` is the amount of images provided in `label_img`, and `W` is the width of each of those images.

**Comment by lanpa** [comment]
Absolutely correct. Will you send a PR?

**Comment by pdpino** [comment]
Sure! I can send a PR soon
