### ISSUE TITLE
Add functionality to add images with bounding boxes, labels, and confidence score.

### ISSUE THREAD

**Issue by ayman-saleh** [lanpa/tensorboardX#517]
Can I write a function inside `writer.py` that will take an image, list of bounding boxes, list of class ids, and list of confidence scores and adds a summary to the events file. In the tensorboard object detection api, there is the ability to do this, and I think this helps with visually profiling the performance of object detection models. Ideally, it would look something like this in `tensorboard`.

![image](https://user-images.githubusercontent.com/30412615/66233336-1d836780-e6b9-11e9-9780-0d7e24330ea0.png)

**Comment by lanpa** [comment]
see:
https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_image_with_boxes

or you can use https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_figure for more complicated labels.
