### ISSUE TITLE
Segmentation fault when run demo.py

### ISSUE THREAD

**Issue by Sibyl233** [lanpa/tensorboardX#526]
when run demo.py, met problem as follow:

> Segmentation fault(core dumped)

My environment:
anaconda3
pytorch 0.4.1
torchvision 0.2.1
tensorboard 2.0.0
tensorboardX 1.9
tensorflow 2.0.0

**Comment by lanpa** [comment]
pytorch is too old. You may use tensorboardX==1.4 if you have to use pytorch 0.4.1

or update to pytorch 1.3 :)
