### ISSUE TITLE
What's the difference between tensorboardX and the integrated tensorboard in pytorch 1.1.0?

### ISSUE THREAD

**Issue by caddyless** [lanpa/tensorboardX#535]
Pytorch 1.1.0 has integrated tensorboard inside, i.e. torch.utils.tensorboard. It seems pytorch native supports tensorboard since 1.1.0. Thus, is there any difference between tensorboardX and the integrated one?

**Comment by lanpa** [comment]
Most of the code is the same, except that `torch.utils.tensorboard` depends on `tensorboard` while logging. Another difference is that tensorboardX supports other frameworks such as chainer, while `torch.utils.tensorboard` is more pytorch specific.
