### ISSUE TITLE
When will PR#528 be in the pip package?

### ISSUE THREAD

**Issue by zcain117** [lanpa/tensorboardX#538]
Looks like v1.9 was released in October and PR#528 went in on Nov 4. I was wondering if that PR be in the next pip release and the rough time estimate for when it might come out. Until then I'll use `pip install 'git+https://github.com/lanpa/tensorboardX'`

Awesome that you added GCS support, thank you!!

**Comment by lanpa** [comment]
By the end of this year. Looks like it works very well.
btw, the thank-you should belong to @wohlert !
