### ISSUE TITLE
Support "None" in hparams?

### ISSUE THREAD

**Issue by richardliaw** [lanpa/tensorboardX#544]
Thanks a bunch for this package. I sometimes have a hyperparameter value that is a Nonetype, but TBX errors when it is passed in. 

I was wondering what the right way to handle this is. Maybe in summary.py, this case should be handled as a `type=DataType.DATA_TYPE_UNSET`?

```
In [2]: from tensorboardX import summary

In [3]: summary.hparams
Out[3]: <function tensorboardX.summary.hparams(hparam_dict=None, metric_dict=None)>

In [4]: summary.hparams({"a": None}, {"score": 1})
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-92757b992968> in <module>
----> 1 summary.hparams({"a": None}, {"score": 1})

~/miniconda3/lib/python3.7/site-packages/tensorboardX/summary.py in hparams(hparam_dict, metric_dict)
    105
    106         if not isinstance(v, int) or not isinstance(v, float):
--> 107             v = make_np(v)[0]
    108             ssi.hparams[k].number_value = v
    109

~/miniconda3/lib/python3.7/site-packages/tensorboardX/x2num.py in make_np(x)
     32         return check_nan(prepare_mxnet(x))
     33     raise NotImplementedError(
---> 34         'Got {}, but expected numpy array or torch tensor.'.format(type(x)))
     35
     36

NotImplementedError: Got <class 'NoneType'>, but expected numpy array or torch tensor.
```

**Comment by lanpa** [comment]
https://github.com/tensorflow/tensorboard/blob/4f3d517a3e1c6a69d21bb784a4d54c1f52830ac8/tensorboard/plugins/hparams/list_session_groups.py#L508
Actually, only number, string, bool are handled in tensorboard now. I use DATA_TYPE_UNSET as a default case.

The workaround is here, would you have a try?
https://github.com/lanpa/tensorboardX/commit/22af48c8041192f294286dd8dfa133ad1b9ffa02

**Comment by ThibzR** [comment]
Hi @lanpa,

Similarly, sometimes hparams may not be a number, string or bool, or even `None`. In my use case, it's a callable.  While I can use this config in @richardliaw's project `ray.tune`, the whole thing crashes because TensorboardX cannot handle that. How about silently discarding the object when not handled instead of raising an exception?
