### ISSUE TITLE
Truncation in Written Values

### ISSUE THREAD

**Issue by SPronav** [lanpa/tensorboardX#547]
**Describe the bug**
It seems that tensorboardX does not actually write the last few values to a file. Running the code below usually truncates off the the last few written values. Specifically, the screenshots show how only values 0 through 476 are being written and plotted. We also waited a few minutes to allow any write buffers to clear.
(One time, all 500 values did appear, so the issue may be non-deterministic...)

**Minimal runnable code to reproduce the behavior**
```
from tensorboardX import SummaryWriter
writer = SummaryWriter()

for i in range(500):
    print(i)
    writer.add_scalar("iter", i, i)
```

**Expected behavior**
A plot of a line with slope 1, starting at (0,0) and going to (499,499)

**Screenshots**
![image](https://user-images.githubusercontent.com/16753290/73089555-81b67b00-3ea4-11ea-8fc6-ddcf79f6df9b.png)
![image](https://user-images.githubusercontent.com/16753290/73089614-a27ed080-3ea4-11ea-9ead-f8f753ddb152.png)

**Environment**
What is the result of 
`pip list|grep -E "torch|proto|tensor"`
If the version is too old, please try to update first.

protobuf             3.11.2
tensorboard          2.1.0
tensorboardX         2.0
torch                1.4.0
torchvision          0.5.0

**Python environment**
Python 3.6.8 with venv and pip

**Additional context**
This issue was replicated on multiple machines with different Python and PyTorch versions.

**Comment by lanpa** [comment]
Hi, you can call `writer.flush()` or `writer.close()` or use the `with SummaryWriter() as writer` statement to make sure everything is written to the disk.
