### ISSUE TITLE
The web page cannot be opened

### ISSUE THREAD

**Issue by lawnostop** [lanpa/tensorboardX#562]
Hi：
   When I wanted to open the tensorboard in the local browser with the url given by the remote server, I found that the web page could not be opened, and it is also not help by changing the browser. MY version is as follow:
1. pytorch 1.3.1
2. tensorboardX 2.0
3. tensorboard 2.0.0

**Comment by lanpa** [comment]
You may need to pass something like `bind_all` in the command line when launching tensorboard server.

**Comment by lawnostop** [comment]
Thank you for your answer, the problem is solved!
