### ISSUE TITLE
Add description option for `add_scalar`

### ISSUE THREAD

**Issue by borea17** [lanpa/tensorboardX#565]
I noticed when hovering over a graph which was created via `SummaryWriter.add_scalar` that each data point has `Name:  .` . It would be nice feature to give each data point a description which would be displayed as `Name`. 

This would be very helpful, e.g., when measuring the accuracy outliers could be easily identified with the corresponding input (e.g., name of image) for further study.

I think tensorflow already has this feature, [see here](https://www.tensorflow.org/api_docs/python/tf/summary/scalar) . (I am not using tensorflow, so not sure whether this function corresponds to the feature I have in mind)

**Comment by lanpa** [comment]
check this for example: 
https://github.com/lanpa/tensorboardX/blob/a31c121e99c4e72de59aaac769a8b44eb89c19ec/examples/demo.py#L26
