### ISSUE TITLE
SummaryWriter.add_scalar() number format and Transforms.TensorboardX

### ISSUE THREAD

**Issue by vpapaioannou** [lanpa/tensorboardX#567]
**1st Question :** How can I control the number format of scalars in TensorboardX board in a graph?

Let's

`# proper imports
writer = SummaryWriter()`
`x = 5.123456789`
`epoch = 3`

If I write, `writer.add_scalar( 'Raw integer scalar', x, epoch)`
everything works fine, but the output format in TensorboardX it varies.

If I write, `writer.add_scalar( 'Formatted raw integer scalar', '{:0.2%}'.format(x), epoch)`
I get this kind of error

`there is no workspace variable`

from line 404, file `tensorboardX/writer.py`

`if self._check_caffe2_blob(scalar_value):`
`    scalar_value = workspace.FetchBlob(scalar_value)`

and there is a check for a Caffe variable although I am using PyTorch.

**2nd Question :** How can I use TensorboardX from Transforms module, what are the dependencies and their minimum versions?

Thanks,
Vassilis

**Comment by lanpa** [comment]
A1: because add_scalar treats string as `caffe`'s blob name. The number format is decided by the TensorBoard webpage. Not sure if truncating the float number yourself helps.

Q2: What is your use case, do you have some code to explain your point?

**Comment by godvNoQ** [comment]
i got this problem too,it seems has not imported workspace.
add from caffe2.python import workspace into writer.
i meet another problem,ImportError:cannot import name 'caffe2_pb2' from 'caffe2.proto'
then,i check the package of caffe2/proto.however,there is not any package in caffe2/proto.

**Comment by mgoldey** [comment]
Also observed in Torch

**Comment by mgoldey** [comment]
Appears to be present with both version 1.9 and 2.0.
Specific error from v1.9 as invoked by huggingface/transformers with pytorch 1.5.0:
```
  File "/scribe/.venv/lib/python3.7/site-packages/tensorboardX/writer.py", line 386, in add_scalar
    scalar_value = workspace.FetchBlob(scalar_value)
```

**Comment by mgoldey** [comment]
The docstring example for `add_scalar` (https://github.com/lanpa/tensorboardX/blob/022f060f9438c4f5e71880bccb474671f5db4450/tensorboardX/writer.py#L400-L405) appears to execute without error when interactively testing

**Comment by mgoldey** [comment]
Possible missing logic here-  add_scalar
invokes 
https://github.com/lanpa/tensorboardX/blob/022f060f9438c4f5e71880bccb474671f5db4450/tensorboardX/writer.py#L300-L313
in https://github.com/lanpa/tensorboardX/blob/022f060f9438c4f5e71880bccb474671f5db4450/tensorboardX/writer.py#L413-L414
but nothing checks that workspace exists

**Comment by mgoldey** [comment]
The specific invocation in transformers could be passing something that's a string type, so this looks like the logic for whether it's in caffe2 is falsely triggering. I think I can suggest a one line fix for this, but there might be a more elegant way.
Specific logic in transformers triggering this issue for me is just a for loop over a dictionary's items.
https://github.com/huggingface/transformers/blob/02e5f79662d72cccdca81a47e3001a5f6d36e5b1/src/transformers/trainer.py#L556-L557

**Comment by mgoldey** [comment]
This error is indeed triggered whenever a string is passed in as the second value of add_scalar. That's because add_scalar expects scalars. That's a perfectly natural assumption for tensorboardX to make. It would be better to throw a different error in this situation, but both my fundamental problem and the OP's problem are not tensorboardX's problem. I would politely suggest throwing a `TypeError` rather than leaving users thinking that they have a package installation problem when they see the `NameError`.

example code to trigger a NameError that probably ought to throw a TypeError
```
from tensorboardX import SummaryWriter
writer = SummaryWriter()
writer.add_scalar("some_variable", "a_string", 0)
```
