### ISSUE TITLE
In a graph, how to show the name of op instead of the puzzling id?

### ISSUE THREAD

**Issue by 1173710126** [lanpa/tensorboardX#573]
![aaa](https://user-images.githubusercontent.com/43494418/79694125-04cb4f80-82a1-11ea-96cd-efaa76e4c1d0.png)
In this graph, the 51 and 53 op is relu, how can the name "relu" shown in the graph instead of the number 51, 53?
Thank you for your answer!

**Comment by CatNofishing** [comment]
I have the similiar problem

**Comment by lanpa** [comment]
Hi all, since the network graph interpretation is highly correlated with the PyTorch JIT (and it changes fast), the graph visualization has been delegated to the core PyTorch team since tensorboardX v2.1. Please make this request at the PyTorch repository.
