### ISSUE TITLE
How to make the histogram interval more precise?

### ISSUE THREAD

**Issue by sicheng7** [lanpa/tensorboardX#581]
Hi!
I try to use histogram to output a series of increasing sequence. The output histogram is cone-shaped instead of spike-shaped. How to make the output more accurate?

**Comment by lanpa** [comment]
https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_histogram

I guess you can make the histogram bin very narrow by setting a proper `bins` value.
