### ISSUE TITLE
tensorboard --logdir=runs issues 

### ISSUE THREAD

**Issue by TanmDL** [lanpa/tensorboardX#583]
AttributeError: module 'tensorflow' has no attribute 'estimator'. 

How do I solve the problem? Please help me.

environments :

tensorboard               2.1.0                     py3_0    anaconda
tensorboardx              2.0                        py_0    conda-forge
tensorflow                2.1.0           gpu_py37h7a4bb67_0    anaconda
tensorflow-base           2.1.0           gpu_py37h6c5654b_0    anaconda
tensorflow-estimator      2.1.0              pyhd54b08b_0    anaconda
tensorflow-gpu            2.1.0                h0d30ee6_0    anaconda

python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2019.3                     py_0  
pywavelets                1.1.1            py37h7b6447c_0  
pyxdg                     0.26                       py_0

**Comment by lanpa** [comment]
can you show the complete error message?

**Comment by TanmDL** [comment]
I have solved it by installing tensorflow through pip.Thank you for your kind reply.
    On Saturday, May 9, 2020, 03:52:17 PM GMT+10, Tzu-Wei Huang <notifications@github.com> wrote:  
 
 


can you show the complete error message?
