### ISSUE TITLE
Installing tensorboardX with pip package name doesn't include  GlobalSummaryWriter

### ISSUE THREAD

**Issue by davzaman** [lanpa/tensorboardX#584]
**Describe the bug**
Installing tensorboardX with `pip install tensorboardX` has different behavior from `pip install 'git+https://github.com/lanpa/tensorboardX'`.  The  latter will include GlobalSummaryWriter, the former will not.

When  using  `pip install tensorboardX`:
```
Traceback (most recent call last):
  File "/home/davina/main.py", line 6, in <module>
    from tensorboardX import GlobalSummaryWriter
ImportError: cannot import name 'GlobalSummaryWriter' from 'tensorboardX' (/home/davina/miniconda3/lib/python3.7/site-packages/tensorboardX/__init__.py)
```
Upon inspecting the `__init__.py` file, I found that it diverged from the `__init__.py` on the repo. It  was missing the following line:  `from .global_writer import GlobalSummaryWriter`. I tried adding it in myself and got the following error: 
```
  File "/home/davina/miniconda3/lib/python3.7/site-packages/tensorboardX/__init__.py", line 7, in <module>
    from .global_writer import GlobalSummaryWriter
ModuleNotFoundError: No module named 'tensorboardX.global_writer'
```

At this point I uninstalled tensorboardX and reinstalled with `pip install 'git+https://github.com/lanpa/tensorboardX'` since  it seemed like  the github repo did have it. This resolved my error.

**Minimal runnable code to reproduce the behavior**
```python
from tensorboardX import GlobalSummaryWriter
```

**Expected behavior**
I expected it  to be  able to import the GlobalSummary writer without error.

**Environment**
```
protobuf                  3.11.2     
tensorboard               2.2.1      
tensorboard-plugin-wit    1.6.0.post3
tensorboardX              2.0+022f060
torch                     1.4.0      
torchvision               0.5.0      
```

**Python environment**
Python  3.7.4
conda 4.8.3

**Comment by lanpa** [comment]
Now you can use it in tensorboardX 2.1 :)
