### ISSUE TITLE
add_images() may be have a BUG

### ISSUE THREAD

**Issue by AaronStuart** [lanpa/tensorboardX#586]
**Describe the bug**
add_images() change img_tensor's dtype from torch.uint8 to np.float, but value doesn't change, still in [0, 255].

**Minimal runnable code to reproduce the behavior**
```
from tensorboardX import SummaryWriter
summary = SummaryWriter('.')

tensor = torch.full([2, 3, 100, 100], fill_value=255, dtype=torch.uint8)
summary.add_images('image', tensor, global_step = 1)
...
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/21955436/82321768-fd19da80-9a07-11ea-8b84-88aa85bda93a.png)

**Environment**
protobuf             3.11.4             
tensorboard          2.1.0              
tensorboardX         2.0                
torch                1.4.0              
torchvision          0.5.0         

**Python environment**
python 3.6.10

**Additional context**

**Comment by lanpa** [comment]
Thanks!
