### ISSUE TITLE
Request for custom logic for visualization

### ISSUE THREAD

**Issue by Aceticia** [lanpa/tensorboardX#587]
For one of my project, I would really want to visualize the predictions per iteration. But the visualization for each iteration is a video which has to be rendered through intense computation, which will significantly slow down the training. Is it possible to add a feature where the raw data can be written to the log, and an additional python script or function can be supplied to tensorboardX to process these raw data?

**Comment by lanpa** [comment]
This is interesting. I have two questions:
1. What is the format of the `raw` data? (un-renered model or rendered png/gif format, etc.)
2. How would you handle the render process if you don't have tensorboardX, will that still slow down the training process significantly?

**Comment by Aceticia** [comment]
Sorry for taking so long to review. We have re-evaluated the necessity of rendering in real time, and concluded a better solution is to store the results and do the processing after we finish training.
