### ISSUE TITLE
The ability to add epoch and batch number in global step

### ISSUE THREAD

**Issue by RSKothari** [lanpa/tensorboardX#588]
It would be great if tensorboardX had this option. It greatly helps observe mean, std and generally improves productivity. 

This step could be followed with a update to data visualization wherein one may click at an epoch and it would expand to show within epoch batch updates.

**Comment by lanpa** [comment]
Hi, I guess what you suggested involves a big modification in the web interface, which should be proposed in `tensorflow/tensorboard` repository. A quick workaround on this is to open a new `summarywriter(logdir=str(epoch_num))` for each new epoch and use another writer to summarize the statistics over each completed epochs.

**Comment by RSKothari** [comment]
I have created a requested on tensorboard git repo. Hopefully they'll add this as an update. https://github.com/tensorflow/tensorboard/issues/3841
