### ISSUE TITLE
Source archives contain byte-compiled .pyc files for Python 2.7

### ISSUE THREAD

**Issue by scdub** [lanpa/tensorboardX#594]
**Describe the bug**
The source archives of the package as hosted on PyPI include 20 .pyc files byte compiled for Python 2.7 (`0x03f3` magic value):

```
$ file tensorboardX/proto/__init__.pyc
tensorboardX/proto/__init__.pyc: python 2.7 byte-compiled
```

**Expected behavior**

The source archives for the package would only contain uncompiled code, and defer to the user to byte compile on the used version of Python.

**Additional context**

This is reproducible with the current [tensorboardX-2.0.tar.gz2](https://files.pythonhosted.org/packages/35/1a/ad6423850fffd22a30fed58a6215858c0413298efb8f5246562b8efffb49/tensorboardX-2.0.tar.gz) archive, and earlier builds. The [staging steps](https://github.com/lanpa/tensorboardX/blob/master/setup.py#L90-L99) listed in setup.py don't seem to produce these for me locally, so it may be something specific to the environment which is generating these archives. Running `uncompile6` on one of the files provided these additional details:

```
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.7.7 (default, Mar 10 2020, 15:43:03)
# [Clang 11.0.0 (clang-1100.0.33.17)]
# Embedded file name: /Users/dexter/git/tensorboardX/tensorboardX/proto/__init__.py
# Compiled at: 2019-08-01 11:57:19
```
@lanpa that looks like that may be your host machine based on other commits.

Let me know if there's any other details I can track down to help.

**Comment by lanpa** [comment]
Thanks. I also found that there are many pyc files in `proto/__pycache__`.
