### ISSUE TITLE
Tensorboardx and tensorboard reduced feature set

### ISSUE THREAD

**Issue by msteijaert** [lanpa/tensorboardX#602]
I use tensorboardx in combination with pytorch in an environment without tensorflow. If I run tensorboard to display the resulting logs, I get a warning `TensorFlow installation not found - running with reduced feature set.`. This makes me wonder if tensorboardx writes any information to the logs that cannot be displayed by tensorboard in the absence of tensorflow. My naive understanding is that this is not the case, but I might be wrong. Can someone comment on this?

I think this should be documented somewhere, or is this already the case?

**Comment by lanpa** [comment]
Hi, For example, you cannot use the profiler, the debugger plugin without tensorflow. And some low level data access pipeline that uses tensorflow's API has a non-tensorflow implementation. The output of tensorboardx or torch.utils.tensorboard should be a subset of tensorboard by this time.

**Comment by msteijaert** [comment]
> The output of tensorboardx or torch.utils.tensorboard should be a subset of tensorboard by this time.

Thanks for your answer. Do I understand correctly, that for the torch + tensorboardx use case the functionality of tensorboard with and without an installed tensorflow should be identical (apart from a warning message)? The additional functionality (e.g. debugger) is not relevant for torch models, is it?

**Comment by lanpa** [comment]
Correct!
