### ISSUE TITLE
Suppress "Warning: NaN or Inf found in input tensor." warning

### ISSUE THREAD

**Issue by Jimmy2027** [lanpa/tensorboardX#604]
Hello,
Is there a way to suppress the "Warning: NaN or Inf found in input tensor." warning message from tensorboardX.SummaryWriter?

**Comment by dzubke** [comment]
Hello @Jimmy2027,

Did you find an answer to your question? If so, what was it? 

Thanks!

**Comment by tangzhimiao** [comment]
maybe try set lr small
