### ISSUE TITLE
How to force the SummaryWriter recording EVERY steps?

### ISSUE THREAD

**Issue by nobodypengium** [lanpa/tensorboardX#605]
Hi there!

I want to record **EVERY** steps while training. I use the following code, but I found that:
1. In the first 1000 steps, it records step 0, step 1, step 2, ..., step 999, step 1000 as I want. (Here the recording interval is 1)
2. After 1000 steps, it seems to **hidden** some recorded scalars, and the record becomes something like step 1, step 5, step 6, step 10, ....., step1001, step 1003, step 1006, step 1007,....
 ``` python
writer = SummaryWriter(log_dir=global_config.log_root)
for epoch in range(opt.n_epochs):
    for i, (imgs, labels) in enumerate(dataloader):

        # ---Training code here-----
        # ---Training code end -----

        # ---Recording code here ---
        batches_done = epoch * len(dataloader) + i # In the debug mode here, batches_done starts with 0 with interval 1, i.e. 0,1,2,3,4,...
        writer.add_scalar("loss/G_loss", g_loss.item(), global_step=batches_done) # but the writer seems to overwrite the recorded values, and only record limited number of scalars.
        writer.add_scalars("loss/loss", {"g_loss": g_loss.item(), "d_loss": d_loss.item()},global_step=batches_done)
```

The step interval is not 1.
![image](https://user-images.githubusercontent.com/13833330/94889382-8f4de700-04ae-11eb-9f77-b3888f446f76.png)

**Comment by lanpa** [comment]
Hi, I can't reproduce the result. I dump the data with: https://github.com/lanpa/tensorboard-dumper

**Comment by nobodypengium** [comment]
> Hi, I can't reproduce the result. I dump the data with: https://github.com/lanpa/tensorboard-dumper

Sorry for bothering, it seems not to be a problem of tensorboardX .

It seems that the ```SummaryWriter``` records every steps. However, the porblem occurs when using ```tensorboard --logdir [LOGDIR]``` to start the WEBUI. Adding args ```--samples_per_plugin scalars=999999999``` can solve the problem.

Here is a [stackoverflow page](https://stackoverflow.com/questions/43702546/tensorboard-doesnt-show-all-data-points) about this.
