### ISSUE TITLE
Tensorboard is not displaying images

### ISSUE THREAD

**Issue by merryHunter** [lanpa/tensorboardX#617]
Hi, running the demo example. It successfully shows scalars, PR curves etc, but not showing images. What do you think may be the problem to this? I'm running it in the nvidia-container https://ngc.nvidia.com/catalog/containers/nvidia:pytorch  ( nvcr.io/nvidia/pytorch:21.02-py3)

This problem also happens if I'm using torch.utils.tensorboard.

Requirements and screenshots attached.
![Screenshot from 2021-03-24 15-53-21](https://user-images.githubusercontent.com/8739446/112322614-bcd75880-8cb9-11eb-9b74-d28b3dd86d9a.png)
![Screenshot from 2021-03-24 15-53-27](https://user-images.githubusercontent.com/8739446/112322620-bd6fef00-8cb9-11eb-9fe5-04438ce6760a.png)

[req.txt](https://github.com/lanpa/tensorboardX/files/6197778/req.txt)

**Comment by lanpa** [comment]
Hi, I am not familiar with docker. Can you test if https://hub.docker.com/r/pytorch/pytorch work? How do you trigger demo.py inside the container? Thanks

**Comment by lanpa** [comment]
I have confirmed the problem is the tensorboard server (`1.15+nv`) inside the ngc docker image. The tensorboard inside the  official docker image works fine. Please reopen the issue if still have problem.

**Comment by merryHunter** [comment]
@lanpa thank you for support! Sure, I should have tried running in another docker image before opening the issue, thanks again for your effort, much appreciated!
