### ISSUE TITLE
No dashboards are active for the current data set

### ISSUE THREAD

**Issue by Hhhhhhhzf** [lanpa/tensorboardX#618]
Firstly I install the tensorboardX using `pip install tensorboardX`.
Then I build a python file named test.py and the content of this file is same to demo.py in readme.
Then I run it.
Finally I start TensorBoard with `tensorboard --logdir runs`.
However, I got 
<img width="685" alt="截屏2021-03-27 下午12 06 27" src="https://user-images.githubusercontent.com/39818832/112709464-e3cd9e80-8ef4-11eb-9037-01e5440dc166.png">

What's wrong with it?
Could some good men tell me why?
I use this lib first time.

my torch version is 1.7. Is this the key problem?
<img width="685" alt="截屏2021-03-27 下午12 02 51" src="https://user-images.githubusercontent.com/39818832/112709512-47f06280-8ef5-11eb-97a9-e1c1e790451f.png">

**Comment by merryHunter** [comment]
Hi @Hhhhhhhzf , can you see the files that have been written to `runs` directory? Usually this message appears in case of no files or in case of wrongly specified path, thus make sure you run this command in the directory containing `runs`.

**Comment by Hhhhhhhzf** [comment]
@merryHunter I see...I find the `runs` directory and I succeed.Thank you for your solution.
