### ISSUE TITLE
tensorboard: command not found

### ISSUE THREAD

**Issue by biggiantpigeon** [lanpa/tensorboardX#628]
I think you have to install tensorflow and tensorboard still, I get it work after install these two.
------------------------------------------------------
I installed tensorboardX1.4 in my conda vitualenv and want to use it with pytorch.
I can now import tensorboardX and generate event files, but when I run
tensorboard --logdir==xxx
I get error: tensorboad: command not found.
I followed the instruction in https://stackoverflow.com/questions/45095820/tensorboard-command-not-found
but I find no main.py under the path.

How can I get it work? Do I need to install tensorboard and tensorflow?

**Comment by vinbo** [comment]
> ## I think you have to install tensorflow and tensorboard still, I get it work after install these two.
> 
> I installed tensorboardX1.4 in my conda vitualenv and want to use it with pytorch.
> I can now import tensorboardX and generate event files, but when I run
> tensorboard --logdir==xxx
> I get error: tensorboad: command not found.
> I followed the instruction in https://stackoverflow.com/questions/45095820/tensorboard-command-not-found
> but I find no main.py under the path.
> 
> How can I get it work? Do I need to install tensorboard and tensorflow?

Hi, I noticed that you closed the question already. I met the same problem. Would you please tell me how you solved the problem? Thank you.

**Comment by biggiantpigeon** [comment]
> you have to install tensorflow and tensorboard

as I said, you have to install tensorflow and tensorboard still.

**Comment by biggiantpigeon** [comment]
> > ## I think you have to install tensorflow and tensorboard still, I get it work after install these two.
> > I installed tensorboardX1.4 in my conda vitualenv and want to use it with pytorch.
> > I can now import tensorboardX and generate event files, but when I run
> > tensorboard --logdir==xxx
> > I get error: tensorboad: command not found.
> > I followed the instruction in https://stackoverflow.com/questions/45095820/tensorboard-command-not-found
> > but I find no main.py under the path.
> > How can I get it work? Do I need to install tensorboard and tensorflow?
> 
> Hi, I noticed that you closed the question already. I met the same problem. Would you please tell me how you solved the problem? Thank you.

as I said, you have to install tensorflow and tensorboard still.

**Comment by vinbo** [comment]
> 
> 
> > > ## I think you have to install tensorflow and tensorboard still, I get it work after install these two.
> > > I installed tensorboardX1.4 in my conda vitualenv and want to use it with pytorch.
> > > I can now import tensorboardX and generate event files, but when I run
> > > tensorboard --logdir==xxx
> > > I get error: tensorboad: command not found.
> > > I followed the instruction in https://stackoverflow.com/questions/45095820/tensorboard-command-not-found
> > > but I find no main.py under the path.
> > > How can I get it work? Do I need to install tensorboard and tensorflow?
> > 
> > 
> > Hi, I noticed that you closed the question already. I met the same problem. Would you please tell me how you solved the problem? Thank you.
> 
> as I said, you have to install tensorflow and tensorboard still.

Solved. Thank you.
