### ISSUE TITLE
How to set tensorboard text with color

### ISSUE THREAD

**Issue by spzhuang** [lanpa/tensorboardX#637]
I want to set text with color via `add_text` method.
I have tried use `<span style="color:red">red</span>` and `<font color="red">red</font>` but it doesn't work.
Because the syn "<", ">" has been changed to `&lt;` and  `&gt;`
I don't know how to solve it.

**Comment by spzhuang** [comment]
I haven't found the answer.
The tensorboard developer hasn't design the word annotation function cause of security. It seem the html function will increase the security risk.
Now I use the markdown table format to real the aim of emphasis word.
This issue can be closed if not anything new viewpoint.

**Comment by lanpa** [comment]
Correct, the security concern. There is another logging service that supports direct html: https://www.comet.ml/docs/python-sdk/Experiment/#experimentlog_html, maybe you can have a try.
