### ISSUE TITLE
Add bert Model

### ISSUE THREAD

**Issue by BttMA** [lanpa/tensorboardX#646]
Hello, I am using tensorboardX to visualise a Bert model on tensorboard with this simple script as it is putted on you documentation :
```
from tensorboardX import SummaryWriter
w = SummaryWriter('runs/Board1')

model = BertForSequenceClassification.from_pretrained("camembert-base",  num_labels=len(label_dict))
dummy_input = next(iter(dataset_train)) #simple input for my training dataset : a list of tensors [input_ids, attention_masks, lables]

w.add_graph(model, dummy_input, True)
```

I keep getting this error and one of them is :

2041         # remove once script supports set_grad_enabled
2042         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2043     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
2044 
2045 

IndexError: index out of range in self

**Comment by tarunbhatiaind** [comment]
How did you resolved this ?

**Comment by BttMA** [comment]
I didn't 😂 . I just used `torchviz`. It is much easier. 

```
from torchviz import make_dot

make_dot(embedding.logits, show_attrs=True, show_saved=True, params=dict(list(model.named_parameters()))) 
   # embedding.logits : output of you model
```
you can also use [Netron](https://github.com/lutzroeder/Netron) if you model is ONNX file 😄
Hope this will help you!
