### ISSUE TITLE
No git tag for 2.4.1

### ISSUE THREAD

**Issue by Mic92** [lanpa/tensorboardX#650]
Also pypi has it: https://pypi.org/project/tensorboardX/
there is no git tag for 2.4.1

**Comment by lanpa** [comment]
Tagged. Does the missing tag broke any of your automation process?

**Comment by Mic92** [comment]
We are building in nixpkgs/NixOS from github to also have tests: https://github.com/NixOS/nixpkgs/blob/e4eed15d8b0af4dfcb8d420c93e039328a968ddd/pkgs/development/python-modules/tensorboardx/default.nix#L26
We rely on tests to verify if the package is still functional

**Comment by Mic92** [comment]
Thx!

**Comment by Mic92** [comment]
I can build a ci pipeline that would auto publish to pypi based on github tags, if that is any help.
