### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by PhilipVinc** [lanpa/tensorboardX#653]
For a while now I've been seeing several deprecation warnings like (see here)[https://github.com/lanpa/tensorboardX/runs/4636642684?check_suite_focus=true#step:6:72])

```python
tensorboardX/proto/resource_handle_pb2.py:57
  /home/runner/work/tensorboardX/tensorboardX/tensorboardX/proto/resource_handle_pb2.py:57: DeprecationWarning: Call to deprecated create function FieldDescriptor(). Note: Create unlinked descriptors is going to go away. Please use get/find descriptors from generated code or query the descriptor_pool.
    _descriptor.FieldDescriptor(
```

they heavily pollute reports by PyTest, so it would be nice if those could be addressed.

**Comment by adamjstewart** [comment]
#654 is not an appropriate fix for this. Everyone who uses tensorboardX as a dependency will also face this warning. The correct solution is to update tensorboardX so that it isn't using deprecated features.

**Comment by lanpa** [comment]
Hi @adamjstewart, this fix only suppress the message in pytest. Please open another issue for production use so I can track it, thanks! (I remember that the deprecation warning only show once per session?)
