### ISSUE TITLE
Protobuf version

### ISSUE THREAD

**Issue by nrudakov** [lanpa/tensorboardX#678]
Any reason why protobuf version is restricted to 3.20.1? https://github.com/lanpa/tensorboardX/blob/9356270bce9e9d7e4f4ecedc85931b89f19a8a14/setup.py#L46
And can it be changed to >=3.8.0,<4 ?

The latest release of onnx requires protobuf >= 3.20.2, < 4 https://github.com/onnx/onnx/blob/ee7d2cdfa34b8b3c7e0b68b70daf72aaa48c23ac/requirements.txt#L2
Therefore, it is not possible to install both tensorboardX and onnx in the same environment without error messages.

**Comment by lanpa** [comment]
Hi, I have updated the requirement to `<=3.20.3` in https://github.com/lanpa/tensorboardX/pull/675. Thank you for pointing this out so I can found this github-bot's PR. XD

**Comment by xkszltl** [comment]
@lanpa It should be <4, not <=3.20.3, protobuf is still release new versions under 3.20, after their renaming of 3.21 to 4.21 with breaking changes.

**Comment by lanpa** [comment]
@xkszltl Updated by @louisoutin in #680. Please have a test!

**Comment by xkszltl** [comment]
Should be good as it's a simple fix and I've suggested it to many libs, including the onnx one referred by @nrudakov 
- https://github.com/onnx/onnx/issues/4532
