### ISSUE TITLE
Remove upper pins on protobuf

### ISSUE THREAD

**Issue by LarsDu** [lanpa/tensorboardX#692]
The upper pin on protobuf in `setup.py` makes TensorboardX uninstallable in certain python conda or poetry environments
https://iscinumpy.dev/post/bound-version-constraints/

I was wondering if this could be remove?

I had to pull tensorboardX entirely out of a certain project due to this upper pin preventing software updates

**Comment by Erotemic** [comment]
I'm having the same issue. I'm being forced to install tensorflow itself in my environment (much to my chagrin) and it is causing the conflict:

```
The conflict is caused by:
    tensorflow 2.12.0 depends on protobuf!=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.20.3
    tensorboard 2.12.0 depends on protobuf>=3.19.6
    tensorboardx 2.5.1 depends on protobuf<=3.20.1 and >=3.8.0
```

**Comment by LarsDu** [comment]
Thanks @lanpa!

**Comment by lanpa** [comment]
Sure! I will do it on weekend.
