### ISSUE TITLE
Possibility of v2.5.2 with upper pin on protobuf of <4?

### ISSUE THREAD

**Issue by DManowitz** [lanpa/tensorboardX#709]
I realize that protobuf 4.x is out now, but would it be possible to release a v2.5.2 of tensorboardX with an upper pin on protobuf of <4, rather than <=3.20.1, as protobuf 3.20 now goes up to 3.20.3, and google-api-core >=2.10.2 doesn't work with 3.20.0 or 3.20.1.

**Comment by lanpa** [comment]
Hi, that would be possible, but does v2.6 or v2.6.1 has compatibility issues for your environment?

**Comment by DManowitz** [comment]
v2.6.1 requires `protobuf>=4.22.3`, which is too high for my environment.

**Comment by lanpa** [comment]
Hi, would you try v2.6.2? I have removed the version limit. And have tested the 3.20 is working. Please have a try. https://github.com/lanpa/tensorboardX/pull/712/files
